feat(web-page-elements): add lesson about actions with web page elements
Atlantis-Academy/frontend-study-ikorol pull request #10
Opened 2020-12-07 14:40 UTC by ikorol3107

ISSUES CLOSED: #9

2020-12-07 16:24 UTC, TorinAsakura requested changes
- все файлы должны именоваться в рамках соглашения, у тебя же в папке icons какой-то мрак, где-то файл именуется через uppercase, где-то через lower
- я увидел минифицированную версию style.css, а где оригинальная?

2020-12-07 16:24 UTC, TorinAsakura commented on lessons/web-page-elements/src/index.js
> +        </li>
это в курсе сказано хакать css через js?

2020-12-07 16:25 UTC, TorinAsakura commented
@ikorol3107 web-page-elements можно понять, когда там элементы, а у тебя тут самая, что ни на есть настоящая страница, называй как есть

2020-12-07 17:49 UTC, ikorol3107 commented on lessons/web-page-elements/src/index.js
> +        </li>
да, это условие задания: поменять верстку используя исключительно js.

2020-12-07 20:53 UTC, TorinAsakura commented on lessons/web-page-elements/src/index.js
> +        </li>
в таком случае твой пакет так и должен называться, а не web-page…

2020-12-08 08:24 UTC, ikorol3107 commented on lessons/web-page-elements/src/index.js
> +        </li>
хочу переименовать пакет на: aktion-with-page-elements . Одобряешь?

2020-12-08 08:26 UTC, TorinAsakura commented on lessons/web-page-elements/src/index.js
> +        </li>
changing-html-via-js

2020-12-09 16:05 UTC, ikorol3107 commented on lessons/web-page-elements/src/index.js
> +        </li>
Название пакета поменяла на changing-html-via-js

2020-12-09 17:36 UTC, TorinAsakura approved these changes

2020-12-09 17:36 UTC, merged