feat(web-page): add a lesson about creating tabs on a web page
Atlantis-Academy/frontend-study-ikorol pull request #14
Opened 2020-12-15 16:56 UTC by ikorol3107

ISSUES CLOSED: #13

2020-12-15 17:04 UTC, TorinAsakura requested changes

2020-12-15 17:04 UTC, TorinAsakura commented on lessons/web-page/package.json
> +  "name": "@lessons/web-page",
подумай

2020-12-16 10:44 UTC, ikorol3107 commented on lessons/web-page/package.json
> +  "name": "@lessons/web-page",
на этой же веб-странице планируется выполнение дальнейших заданий (создание таймера, модального окна, слайдера и т.д.), будет полноценная веб-страница, поэтому назвала так пакет.

2020-12-16 10:49 UTC, TorinAsakura commented on lessons/web-page/package.json
> +  "name": "@lessons/web-page",
> на этой же веб-странице планируется выполнение дальнейших заданий (создание таймера, модального окна, слайдера и т.д.), будет полноценная веб-страница, поэтому назвала так пакет.

Постарайся, в таком случае, чтобы каждая задача была вынесена отдельно

2020-12-16 10:49 UTC, TorinAsakura approved these changes

2020-12-16 10:49 UTC, merged