feat(call-context-this): add a lesson about function call context this
Atlantis-Academy/frontend-study-ikorol pull request #23
Opened 2020-12-22 12:45 UTC by ikorol3107

ISSUES CLOSED: #22

2020-12-28 21:40 UTC, TorinAsakura requested changes

2020-12-28 21:40 UTC, TorinAsakura commented on lessons/call-context-this/src/index.js
> +// 1) Обычная функция: this = window, если есть use strict - undefined
Комментирование кода должно проводиться на латинице

2020-12-28 21:40 UTC, TorinAsakura commented on lessons/call-context-this/src/index.js
> +// 2) Контекст у методов объекта - сам объект
Формат комментирования кода используй рекомендованный JDoc
@themetronome помоги ей если что пойдёт не так

2020-12-29 20:30 UTC, TorinAsakura submitted a review, later dismissed

2020-12-29 20:31 UTC, TorinAsakura commented
@ikorol3107 коммиты не подписаны: переделывай

2020-12-30 09:14 UTC, ikorol3107 commented
делала только-что коммит в тестовом репозитории - все подписалось, а здесь почему-то нет

2020-12-30 09:17 UTC, themetronome commented
> делала только-что коммит в тестовом репозитории - все подписалось, а здесь почему-то нет

автоподпись не настроена

2020-12-30 10:24 UTC, TorinAsakura approved these changes, later dismissed

2020-12-30 10:24 UTC, TorinAsakura commented
@ikorol3107 6647fb2b3941fb9ba7cd8641401a9450d532b5a2 этот коммит не подписан и блокирует merge

2020-12-30 16:16 UTC, themetronome approved these changes

2020-12-30 19:35 UTC, TorinAsakura approved these changes

2020-12-30 19:36 UTC, merged