chore(frontend-study-ikorol): add configuration files
Atlantis-Academy/frontend-study-ikorol pull request #26
Opened 2021-01-04 13:36 UTC by ikorol3107

affects: @lessons/call-context-this, @lessons/events-and-handlers, @lessons/functions-and-methods,
@lessons/how-to-js, @lessons/loops-and-conditions, @lessons/objects, @practice/changing-html-via-js,
@practice/web-page

add configuration files to project and all packages

ISSUES CLOSED: #25

2021-01-04 13:49 UTC, TorinAsakura requested changes

2021-01-04 13:49 UTC, TorinAsakura commented on lessons/call-context-this/tsconfig.json
> +  "extends": "@atlantis-lab/tsconfig/tsconfig.lib.json",
зачем ты берёшь tsconfig для библиотек?

2021-01-04 13:49 UTC, TorinAsakura commented on lessons/call-context-this/tsconfig.json
> +  "exclude": ["node_modules"],
Это зачем?

2021-01-04 13:49 UTC, TorinAsakura commented on tsconfig.json
> +  ]
зачем?

2021-01-04 13:49 UTC, TorinAsakura commented on tsconfig.json
> +}
LN

2021-01-04 13:55 UTC, TorinAsakura commented
Что за дичь у тебя в скоупе?

2021-01-04 14:13 UTC, ikorol3107 commented on lessons/call-context-this/tsconfig.json
> +  "exclude": ["node_modules"],
`compilerOptions` отвечает за настройку параметров компиляции. Здесь я задала `allowJs` "true" , чтоб при компиляции, если еще нет файлов `.ts` не выскакивала ошибка. 
`outDir` помещает все скомпилированные файлы в папку "dist". 
`exclude` исключает указанный файл при компиляции.

2021-01-04 14:23 UTC, ikorol3107 commented on tsconfig.json
> +  ]
использовала `include` , чтоб компилировать все файлы, находящиеся в заданных папках, чтоб не перечислять эти  файлы с помощью списка относительных путей в `files`

2021-01-04 14:37 UTC, ikorol3107 commented on lessons/call-context-this/tsconfig.json
> +  "extends": "@atlantis-lab/tsconfig/tsconfig.lib.json",
здесь честно не могу ответить на вопрос. Написала не подумав, мой косяк. А сейчас ты спросил и я поняла, что мы пока в проекте не используем библиотеки.

2021-01-04 14:40 UTC, ikorol3107 commented
> Что за дичь у тебя в скоупе?

так как изменения касаются всех пакетов, выделила все при создании коммита.

2021-01-04 15:27 UTC, TorinAsakura commented
> > Что за дичь у тебя в скоупе?
> 
> так как изменения касаются всех пакетов, выделила все при создании коммита.

нет скоупа, раз все три

2021-01-04 19:58 UTC, TorinAsakura requested changes

2021-01-04 19:58 UTC, TorinAsakura commented on lessons/call-context-this/tsconfig.json
> +  "extends": "@atlantis-lab/tsconfig/tsconfig.lib.json",
вот беда ведь...для начала изучи то, что находится внутри этих конфигов, там их несколько и каждый для своих целей. В данный момент ты взяли тсконфиг для кастомных библиотек которые я пишу, у тебя тут не библиотека а бейзик прожект, значит должен быть общий конфиг, а все частные должны просто от него наследоваться

2021-01-04 19:58 UTC, TorinAsakura commented on lessons/call-context-this/tsconfig.json
> +  "exclude": ["node_modules"],
А ты вообще смотрела, что находится внутри тсконфига который ты импортишь?

2021-01-05 09:45 UTC, ikorol3107 commented on lessons/call-context-this/tsconfig.json
> +  "extends": "@atlantis-lab/tsconfig/tsconfig.lib.json",
@TorinAsakura Андрей,  мне сейчас в этом проекте может лучше самой написать конфиг файл ,  следуя  документации TS, и не брать твои? Или взять твой базовый? Что будет правильней?

2021-01-05 09:48 UTC, ikorol3107 commented on lessons/call-context-this/tsconfig.json
> +  "exclude": ["node_modules"],
смотрела. Т.к. здесь использовала конфиг для библиотек, который наследуется от базового, то там уже есть `exclude` - значит можно его не дублировать, ты это имеешь в виду в вопросе?

2021-01-05 15:05 UTC, themetronome commented on package.json
> +    "@atlantis-lab/tsconfig": "^0.1.2"
tsconfig to devDependencies

2021-01-08 21:50 UTC, TorinAsakura commented on lessons/call-context-this/tsconfig.json
> +  "extends": "@atlantis-lab/tsconfig/tsconfig.lib.json",
> @TorinAsakura Андрей, мне сейчас в этом проекте может лучше самой написать конфиг файл , следуя документации TS, и не брать твои? Или взять твой базовый? Что будет правильней?

Доступ к репе открыт уже давно, ты можешь посмотреть конфиги и взять нужный

2021-01-08 21:50 UTC, TorinAsakura commented on lessons/call-context-this/tsconfig.json
> +  "exclude": ["node_modules"],
> смотрела. Т.к. здесь использовала конфиг для библиотек, который наследуется от базового, то там уже есть `exclude` - значит можно его не дублировать, ты это имеешь в виду в вопросе?

верно

2021-01-08 21:51 UTC, TorinAsakura commented on tsconfig.json
> +  ]
> использовала `include` , чтоб компилировать все файлы, находящиеся в заданных папках, чтоб не перечислять эти файлы с помощью списка относительных путей в `files`

маска задана неверно (излишне) и этого делать не нужно, так как в каждый проект помещается свой тсконфиг который наследуется от общего

2021-01-08 21:52 UTC, TorinAsakura reviewed
Проблема та же что и у @themetronome - тсконфиг должен быть один базовый, остальные должны от него наследоваться

2021-01-08 21:52 UTC, TorinAsakura commented on package.json
> +    "@atlantis-lab/tsconfig": "^0.1.2"
@ikorol3107 ^

2021-01-09 12:21 UTC, TorinAsakura requested changes
полагаю, dist можно вынести в общий, а вот allowJS я бы убрал, мы переезжаем на тс и он нам тут не пригодится

2021-01-11 13:20 UTC, TorinAsakura requested changes
Зачем ты вынесла outDir на уровень выше? Верни как было…

2021-01-11 20:48 UTC, themetronome approved these changes

2021-01-12 19:21 UTC, TorinAsakura approved these changes

2021-01-12 19:21 UTC, merged