refactor: move lessons packages to ts
Atlantis-Academy/frontend-study-ikorol pull request #28
Opened 2021-01-13 10:25 UTC by ikorol3107

ISSUES CLOSED: #24

2021-01-13 15:46 UTC, TorinAsakura requested changes

2021-01-13 15:46 UTC, TorinAsakura commented on lessons/objects/src/index.html
> +<script src='../dist/index.js'></script>
это очень интересно…вот только твои js файлы лежат в папке src…

2021-01-14 09:05 UTC, ikorol3107 commented on lessons/objects/src/index.html
> +<script src='../dist/index.js'></script>
в src у меня лежат ts файлы, а js файлы при компиляции создаются в папке dist...

2021-01-14 09:19 UTC, themetronome commented on lessons/objects/src/index.html
> +<script src='../dist/index.js'></script>
> в src у меня лежат ts файлы, а js файлы при компиляции создаются в папке dist...

они только там и должны лежать в таком случае

2021-01-14 09:41 UTC, ikorol3107 commented on lessons/objects/src/index.html
> +<script src='../dist/index.js'></script>
> > в src у меня лежат ts файлы, а js файлы при компиляции создаются в папке dist...
> 
> они только там и должны лежать в таком случае

не поняла твою фразу, про что именно ты?

2021-01-14 10:31 UTC, themetronome commented on lessons/objects/src/index.html
> +<script src='../dist/index.js'></script>
> > > в src у меня лежат ts файлы, а js файлы при компиляции создаются в папке dist...
> > 
> > 
> > они только там и должны лежать в таком случае
> 
> не поняла твою фразу, про что именно ты?

сейчас в каждом пакете, в index.html, у тебя указан путь на index.js в dist. но в то же время у тебя index.js лежит в src. если ты компилишь .js в dist, то он только там и должен лежать

2021-01-14 10:53 UTC, ikorol3107 commented on lessons/objects/src/index.html
> +<script src='../dist/index.js'></script>
> > > > в src у меня лежат ts файлы, а js файлы при компиляции создаются в папке dist...
> > > 
> > > 
> > > они только там и должны лежать в таком случае
> > 
> > 
> > не поняла твою фразу, про что именно ты?
> 
> сейчас в каждом пакете, в index.html, у тебя указан путь на index.js в dist. но в то же время у тебя index.js лежит в src. если ты компилишь .js в dist, то он только там и должен лежать

так он там и лежит. У меня нет в `src` js файлов нигде. Я сначала переименовывала файл с .js на .ts , а потом уже вносила изменения. Я не понимаю почему в измененных файлах показывает , что там js файлы, я так понимаю это из.за них вопрос возник .

2021-01-14 10:57 UTC, TorinAsakura commented on lessons/objects/src/index.html
> +<script src='../dist/index.js'></script>
Если показывает - значит есть

2021-01-14 11:45 UTC, TorinAsakura approved these changes

2021-01-14 11:53 UTC, merged

2021-01-14 11:53 UTC, themetronome approved these changes