Chore: ts code refactor
Atlantis-Academy/frontend-study-ikorol pull request #39
Opened 2021-01-23 12:33 UTC by ikorol3107

ISSUES CLOSED: #38

2021-01-23 21:48 UTC, themetronome submitted a review, later dismissed

2021-01-26 13:14 UTC, themetronome requested changes

2021-01-26 13:14 UTC, ad21ewda1231dsa123das12 commented on lessons/how-to-js/src/index.ts
> +  movieGenres: string[]
То, что речь идёт о фильмах, понятно из контекста. Предлагаю оставить просто `genres`

2021-01-26 13:14 UTC, ad21ewda1231dsa123das12 commented on lessons/how-to-js/src/index.ts
>    privat: boolean
private

2021-01-26 13:14 UTC, ad21ewda1231dsa123das12 commented on lessons/how-to-js/src/index.ts
> +  movieGenres: [],
То, что речь идёт о фильмах, понятно из контекста. Предлагаю оставить просто `genres`

2021-01-26 13:14 UTC, ad21ewda1231dsa123das12 commented on lessons/how-to-js/src/index.ts
>    privat: false,
private

2021-01-26 13:14 UTC, ad21ewda1231dsa123das12 commented on lessons/loops-and-conditions/src/index.ts
> +} while (requestsNumber < 2)
Оставь один из методов решения

2021-01-26 13:14 UTC, ad21ewda1231dsa123das12 commented on lessons/objects/src/index.ts
>          i--
Не забудь поправить здесь, и убрать правило из еслинт конфига в пакете

2021-01-26 13:14 UTC, ad21ewda1231dsa123das12 commented on lessons/call-context-this/src/index.ts
> +function showThis(a: number, b: number) {
Здесь правки проговорили. Как предложение: можно придумать какой-то пример в рамках которого аргументы в поля объектов будут вполне читабельными и понятными

2021-01-26 13:14 UTC, ad21ewda1231dsa123das12 commented on lessons/call-context-this/src/index.ts
>  const obj: { a: number; b: number; sum: () => void } = {
Здесь правки проговорили. Как предложение: можно придумать какой-то пример в рамках которого аргументы в поля объектов будут вполне читабельными и понятными

2021-01-26 13:14 UTC, themetronome commented on practice/web-page/src/ts/index.ts
>        const t = getTimeRemaining(endTime)
t?

2021-01-27 20:32 UTC, themetronome approved these changes

2021-02-01 22:24 UTC, themetronome requested changes

2021-02-01 22:24 UTC, themetronome commented on lessons/events-and-handlers/src/index.ts
> +  const newMoviePoster: string = "url('../img/bg.jpg')"
Нет никаких проблем чтобы передавать путь нового постера просто виде аргумента

2021-02-01 22:24 UTC, themetronome commented on lessons/functions-and-methods/src/index.ts
> +  movieGenres: [],
genres

2021-02-01 22:24 UTC, themetronome commented on lessons/functions-and-methods/src/index.ts
>    privat: false,
private

2021-02-01 22:24 UTC, themetronome commented on lessons/objects/src/index.ts
> +  start() {
start - оторванное от контекста название, на мой взгляд

2021-02-01 22:24 UTC, themetronome commented on practice/changing-html-via-js/src/index.ts
> +movieGenre.forEach((item) => {
genre

2021-02-01 22:24 UTC, themetronome commented on practice/web-page/src/index.ts
> +  function setClock(selector: any, endTime: string) {
selector, вроде, должен передасться в виде строки в `querySelector`

2021-02-02 12:45 UTC, themetronome approved these changes

2021-02-02 14:45 UTC, TorinAsakura approved these changes

2021-02-02 15:04 UTC, merged