feat(web-page): add sending data to server and user reply module
Atlantis-Academy/frontend-study-ikorol pull request #44
Opened 2021-02-08 15:25 UTC by ikorol3107

affects: @practice/web-page

ISSUES CLOSED: #42

2021-02-08 17:39 UTC, themetronome requested changes
Все вроде хорошо и по структуре и по неймингу. Единственный момент не понял с присвоением переменной, а потом в условии строчкой ниже она не используется

2021-02-08 17:39 UTC, ad21ewda1231dsa123das12 commented on practice/web-page/src/index.ts
> +    if (e.target === modalWindow || el.getAttribute('data-close') === '') {
el === modalWindow?

2021-02-08 18:49 UTC, ikorol3107 commented on practice/web-page/src/index.ts
> +    if (e.target === modalWindow || el.getAttribute('data-close') === '') {
Тайпскрипт ругался на getAttribute, писал что "Property 'getAttribute' does not exist.." , поэтому я добавила HTMLInputElement как тип event.target и сразу в след строке использовала эту переменную `el` .

2021-02-09 08:46 UTC, themetronome commented on practice/web-page/src/index.ts
> +    if (e.target === modalWindow || el.getAttribute('data-close') === '') {
> Тайпскрипт ругался на getAttribute, писал что "Property 'getAttribute' does not exist.." , поэтому я добавила HTMLInputElement как тип event.target и сразу в след строке использовала эту переменную `el` .

Я имею в виду, почему при строгом сравнении не используешь переменную, а e.target, чьё значение ты в переменную и присвоила

2021-02-09 13:16 UTC, themetronome approved these changes

2021-02-10 06:59 UTC, TorinAsakura approved these changes

2021-02-10 06:59 UTC, merged