feat(web-page): add functionality to the slider
Atlantis-Academy/frontend-study-ikorol pull request #50
Opened 2021-02-16 12:48 UTC by ikorol3107

affects: @practice/web-page

ISSUES CLOSED: #48

2021-02-16 13:17 UTC, themetronome requested changes

2021-02-16 13:17 UTC, themetronome commented on practice/web-page/src/index.ts
> +  }
Не лепи блоки кода друг к другу, раздели их семантически. Функцию от функции. Внутри блока функции, условия тоже можно разбить, так код будет выглядеть гораздо читабельнее

2021-02-16 13:17 UTC, themetronome commented on practice/web-page/src/index.ts
> +          <div class="menu__item-descry">${this.description}</div>
Это как получилось так?

2021-02-16 13:17 UTC, themetronome commented on practice/web-page/public/index.html
> +                        <img src="../src/assets/img/slider/oliveOil.jpg" alt="oil">
Скорее всего, надо вернуть кебабкейс. @TorinAsakura подскажи пожалуйста

2021-02-16 13:38 UTC, ikorol3107 commented on practice/web-page/src/index.ts
> +          <div class="menu__item-descry">${this.description}</div>
ху ноус... :-/ , где-то по дороге потерялась одна буква, из-за нее верстка поехала.

2021-02-16 16:04 UTC, themetronome submitted a review, later dismissed

2021-02-16 20:59 UTC, TorinAsakura requested changes

2021-02-16 20:59 UTC, TorinAsakura commented on practice/web-page/public/index.html
> +                        <img src="../src/assets/img/slider/oliveOil.jpg" alt="oil">
вообще тут тоже ке-баб нужен, кеймелКейс нужен для именования компонентов, а всё файло и фолдеры по кебабу, за некоторым исключением

2021-02-16 20:59 UTC, TorinAsakura commented on practice/web-page/src/index.ts
> +          <div class="menu__item-descry">${this.description}</div>
а что такое descry? oO

2021-02-17 09:29 UTC, themetronome approved these changes, later dismissed

2021-02-17 12:36 UTC, TorinAsakura requested changes

2021-02-17 12:36 UTC, TorinAsakura commented on practice/web-page/public/index.html
> +                        <img src="../src/assets/img/slider/food12.jpg" alt="food">
через кебаб было правило, должно быть читабельно
если читать через кеймел - больше похоже на foodl2

2021-02-17 12:57 UTC, themetronome approved these changes

2021-02-17 14:37 UTC, TorinAsakura approved these changes

2021-02-17 14:37 UTC, merged