feat(web-page): add pagination points for the slider
Atlantis-Academy/frontend-study-ikorol pull request #53
Opened 2021-02-18 09:10 UTC by ikorol3107

affects: @practice/web-page

ISSUES CLOSED: #51

2021-02-18 10:00 UTC, themetronome approved these changes, later dismissed

2021-02-19 14:44 UTC, TorinAsakura requested changes

2021-02-19 14:44 UTC, TorinAsakura commented on practice/web-page/src/css/style.css
> +.dot {
ставь вопрос - "чей"
тут вот нихера не понятно, а вот ниже ты объявила в имени переменной, что это sliderDots
Так в чём же проблема?

2021-02-19 19:38 UTC, themetronome submitted a review, later dismissed

2021-02-20 09:23 UTC, TorinAsakura requested changes

2021-02-20 09:23 UTC, TorinAsakura commented on practice/web-page/src/css/style.css
> +.sliderDot {
так карусель или слайдер?

2021-02-20 09:44 UTC, themetronome commented on practice/web-page/src/css/style.css
> +.sliderDot {
> так карусель или слайдер?

Слайдер. @ikorol3107 сделай имя класса более подходящим, например _sliderIndicators_ или _sliderBullets_

2021-02-20 10:29 UTC, themetronome approved these changes

2021-02-22 15:11 UTC, TorinAsakura approved these changes

2021-02-22 15:11 UTC, merged