chore/update projects structure
Atlantis-Academy/frontend-study-ikorol pull request #66
Opened 2021-03-17 18:50 UTC by ikorol3107

2021-03-26 08:51 UTC, TorinAsakura requested changes

2021-03-26 08:51 UTC, TorinAsakura commented on practice/my-diary/components/post-list/src/PostList.tsx
> +        <Box alignItem='center !important' display='flex !important' margin='0'>
зачем у тебя здесь используется important ?

2021-03-26 08:51 UTC, TorinAsakura commented on practice/my-diary/components/app-header/src/AppHeader.tsx
> +      <h1>{name}</h1>
не используй нативные элементы HTML API, так как они тянут за собой генерируемые стили

2021-03-26 08:51 UTC, TorinAsakura commented on practice/my-diary/site/app/src/App.tsx
> +        { note: 'Ich möchte eine Reise machen' },
Шутишь? Используй English

2021-03-26 08:51 UTC, TorinAsakura commented on practice/my-diary/site/app/src/App.tsx
> +          <Button color='blue' borderRadius='0.25em 0 0 0.25em'>
почему border radius у тебя в em?

2021-03-26 08:51 UTC, TorinAsakura commented on practice/my-diary/site/app/src/App.tsx
> +interface AppProps {}
это тут для чего?

2021-03-26 08:51 UTC, TorinAsakura commented on practice/my-diary/site/app/src/App.tsx
> +interface AppState {
зачем?

2021-03-26 08:51 UTC, TorinAsakura commented on practice/my-diary/ui/icons/src/HeartIcon.tsx
> +  -webkit-font-smoothing: antialiased;
зачем тебе вендор-префиксы?

2021-03-26 08:51 UTC, TorinAsakura commented on practice/my-diary/ui/input/src/Input.tsx
> +  height: 1.5em;
высоту/ширину и вообще дименшены задаём в пикселях

2021-03-26 08:51 UTC, TorinAsakura commented on practice/my-diary/ui/input/src/Input.tsx
> +  padding: 0.375rem 0.75rem;
тоже самое

2021-03-29 14:28 UTC, TorinAsakura requested changes

2021-03-29 14:28 UTC, TorinAsakura commented on practice/my-diary/components/app-header/src/AppHeader.tsx
> +    <Box justifyContent='space-between' alignItems='flex-end' display='flex'>
пропсы именуются через LOWER camelCase

2021-03-29 14:28 UTC, TorinAsakura commented on practice/my-diary/components/post-list/src/PostList.tsx
> +const StyledPostList = styled.ul`
А зачем ты рестилизовываешь ul? Ты не можешь сделать список без ul?

2021-03-29 14:28 UTC, TorinAsakura commented on practice/my-diary/components/post-list/src/PostList.tsx
> +export const PostList = ({ notes }) => {
это неверная конструкция, PostList слишком привязано к контексту, должен быть просто list, который бы подходил тебе по требованиям проекта

2021-03-29 14:28 UTC, TorinAsakura commented on practice/my-diary/components/post-list/src/PostList.tsx
> +        <Text cursor='pointer' lineHeight='35px'>
Text не должен выглядеть как ссылка

2021-03-29 14:28 UTC, TorinAsakura commented on practice/my-diary/components/post-list/src/PostList.tsx
> +  return <StyledPostList>{elements}</StyledPostList>
Это тут зачем?

2021-03-29 14:28 UTC, TorinAsakura commented on practice/my-diary/site/app/tsconfig.json
> +    "module": "commonjs",
зачем? Если мы используем esm?

2021-03-29 14:28 UTC, TorinAsakura commented on practice/my-diary/site/app/tsconfig.json
> +    "allowSyntheticDefaultImports": true
зачем?

2021-03-29 15:52 UTC, TFK70 commented on practice/my-diary/ui/input/src/Input.tsx
> +  padding: 6px 10px;
Обычно мы оформляем подобное таким образом:
```javascript
styled('input')(({ width, height,...props }) => ({
   display: 'block',
   width,
   height
   ....и тд
}))
```
Так проще работать с пропсами

2021-03-29 17:34 UTC, ikorol3107 commented on practice/my-diary/components/app-header/src/AppHeader.tsx
> +    <Box justifyContent='space-between' alignItems='flex-end' display='flex'>
я их так и именую: первая буква всего слова является строчной, а последующие первые буквы - прописными.

2021-03-29 18:04 UTC, TorinAsakura commented on practice/my-diary/components/app-header/src/AppHeader.tsx
> +    <Box justifyContent='space-between' alignItems='flex-end' display='flex'>
> я их так и именую: первая буква всего слова является строчной, а последующие первые буквы - прописными.

space-between

2021-03-30 06:28 UTC, ikorol3107 commented on practice/my-diary/site/app/tsconfig.json
> +    "module": "commonjs",
я могу тогда в конфиге вебпака поменять синтаксис на cjs? Потому-что если я использую настройки атлантис-лаб конфига (module": "esnext" ), то ошибка при загрузке вебпак конфига - отказывается распознавать ключевое слово  export

2021-03-30 14:15 UTC, TFK70 requested changes

2021-03-30 14:15 UTC, TFK70 commented on practice/my-diary/ui/button/src/types.tsx
> +export interface StyledButtonProps {
Почему у файла расширение tsx? JSX здесь вроде нет

2021-03-30 14:15 UTC, TFK70 commented on practice/my-diary/ui/button/src/types.tsx
> +  borderRadius?: string | number
И раз уж ты используешь styled-system то возьми типы оттуда
```javascript
import { BorderProps } from 'styled-system'
```
И заэкстендись от него:
Так же сделай для color и т.д., не нужно будет кучу пропсов руками описывать

2021-03-30 14:15 UTC, TFK70 commented on practice/my-diary/ui/button/package.json
> +    "@types/styled-system": "^5.1.10",
types должны быть в дев зависимостях
типизация нужна только при разработке

2021-03-30 14:15 UTC, TFK70 commented on practice/my-diary/ui/input/src/Input.tsx
> +const StyledInput = styled('input')(({ width, height, ...props }) => ({
width и height я указал лишь для примера, это не единственные свойства которые было бы неплохо конфигурировать снаружи
У меня вполне может возникнуть потребность использовать другой бордер или фонт сайз (например)
И  опять же, раз уж ты используешь styled-system - используй этот инструмент и здесь: это очень удобно написать одно слово чтобы описать все пропсы относящиеся к конфигурации размеров элемента

2021-03-30 14:15 UTC, TFK70 commented on practice/my-diary/ui/input/src/Input.tsx
> +const StyledInput = styled('input')(({ width, height, ...props }) => ({
Но а если необходимо значение по умолчанию - стоит добавить defaultProps

2021-03-30 14:15 UTC, TFK70 commented on practice/my-diary/ui/input/src/Input.tsx
> +  const inputProps = props
Зачем? Используй деструктор

2021-03-30 14:15 UTC, TFK70 commented on practice/my-diary/ui/input/package.json
>    "main": "src/index.tsx",
Индексам тоже нет смысла оставлять расширение tsx раз уж там  jsx нигде нет

2021-03-30 14:15 UTC, TFK70 commented on practice/my-diary/ui/layout/package.json
> +    "@types/styled-system": "^5.1.0",
В дев

2021-03-30 14:15 UTC, TFK70 commented on practice/my-diary/site/app/package.json
> +    "typescript": "^4.1.2",
typescript, как и типы, тоже нужен только при разработке

2021-03-30 14:15 UTC, TFK70 commented on practice/my-diary/ui/layout/src/Box.tsx
> +    'Roboto',
Куда столько?
Оставь из всех стилей в боксе только нужные, с таким успехом можно было и полностью компонент из uikit заимпортить, копипасты вообще ни к чему

2021-03-30 14:15 UTC, TFK70 commented on practice/my-diary/ui/button/src/Button.tsx
> +const StyledButton = styled('button', { shouldForwardProp })<StyledButtonProps>(
Аналогично боксу
Опиши компонент проще, без лишнего, главное - самостоятельно

2021-03-30 17:38 UTC, TFK70 commented
@ikorol3107 а почему у тебя my-diary как следует не оформлен?
У тебя должен быть воркспейс @practice/my-diary, а в нем все необходимые скрипты для запуска проекта, как в web-page

2021-04-01 10:35 UTC, TorinAsakura commented on practice/my-diary/ui/input/package.json
>    "main": "src/index.tsx",
> Индексам тоже нет смысла оставлять расширение tsx раз уж там jsx нигде нет

расширение всегда нужно ставить

2021-04-01 10:39 UTC, TFK70 commented on practice/my-diary/ui/input/package.json
>    "main": "src/index.tsx",
> > Индексам тоже нет смысла оставлять расширение tsx раз уж там jsx нигде нет
> 
> расширение всегда нужно ставить при указателе в пекедже

я к тому что его стоит переименовать просто в ts

2021-04-01 16:27 UTC, TFK70 requested changes

2021-04-01 16:27 UTC, TFK70 commented on practice/my-diary/ui/layout/src/Box.tsx
> +  fontFamily,
Нет смысла описывать так много пропсов, большинство из них включают в себя функции из styled-system:
fontFamily, fontSize и т.д. входят в typography
boxShadow входит в shadow
justifyContent, alignItems входят в flexbox (который ты, кстати, уже здесь используешь, так что в них тем более нет смысла)
И т.д. Больше информации, как обычно, [тут](https://styled-system.com/api)

2021-04-01 19:46 UTC, TFK70 approved these changes

2021-04-01 22:45 UTC, TorinAsakura commented on practice/my-diary/components/app-header/src/AppHeader.tsx
> +export const AppHeader = ({ name, text }) => {
ну, нам не нужно напоминать продавцу в магазине, что мы пришли что-то купить… - достаточно назвать header, тут и так всё понятно

2021-04-01 22:47 UTC, TorinAsakura commented on practice/my-diary/package.json
> +  "main": "index.js",
а где он у тебя живёт-то?

2021-04-01 22:50 UTC, TorinAsakura commented on practice/web-page/webpack.config.js
> +const path = require('path')
этот конфиг просто остался откуда-то или что это? ну, почему он в формате cjs и не в ts?

2021-04-01 22:50 UTC, TorinAsakura approved these changes
В целом ок, остальное поправишь в следующем ПРе

2021-04-01 22:50 UTC, merged