feat(my-diary): add ability to mark status in list items
Atlantis-Academy/frontend-study-ikorol pull request #67
Opened 2021-04-04 07:57 UTC by ikorol3107

affects: @components/header, @components/list, @practice/my-diary, @site/app, @ui/button, @ui/item

ISSUES CLOSED: #62

2021-04-04 08:02 UTC, TFK70 requested changes

2021-04-04 08:02 UTC, TFK70 commented on practice/my-diary/components/list/src/List.tsx
> +    const [isLiked, setIsLiked] = useState(null)
Нет, без нулей
Если у isLiked тип boolean то ты initial state и ставь boolean

2021-04-04 08:40 UTC, TFK70 submitted a review, later dismissed

2021-04-04 16:27 UTC, TorinAsakura requested changes

2021-04-04 16:27 UTC, TorinAsakura commented on practice/my-diary/package.json
> +  "main": "site/app/src/index.tsx",
и что это? а главное как ты планируешь сделать это рабочим?))

2021-04-04 16:27 UTC, TorinAsakura commented on practice/my-diary/site/app/package.json
> +    "@components/header": "0.0.0"
header тоже, типа, ui компонент)

2021-04-05 12:29 UTC, ikorol3107 commented on practice/my-diary/site/app/package.json
> +    "@components/header": "0.0.0"
Получается я могу в ui-компоненте использовать  несколько других ui компонентов?

2021-04-05 15:17 UTC, TFK70 requested changes

2021-04-05 15:17 UTC, TFK70 commented on practice/my-diary/site/app/src/App.tsx
> +      <Header name='Irina Korol' text='5 posts 4 liked' />
Я не думаю что ты так часто меняешь имя, что его извне в пропсах передаешь) Его даже через интл можно пробросить

С text аналогично: хедер реализует конкретный кусок логики. Его задача - отобразить твое имя (которое +- константное) и отобразить количество постов. Раз у этого компонента цель всегда одна и он всегда работает с одними и теми же данными которые берутся из одного и того же места, а еще он не такой уж и реиспользуемый - есть ли смысл конфигурировать его извне с помощью пропсов и уж тем более держать в ui?

2021-04-05 15:17 UTC, TFK70 commented on practice/my-diary/ui/item/src/Item.tsx
>  export const Item = styled.li(
А тут какое-то очень странное разделение произошло
Item - вряд ли самостоятельный компонент, ты наверняка хочешь использовать его вместе с list, значит он и находиться должен там же, в листе

А вот почему у тебя лист находится в components - большой вопрос. Он не отвечает у тебя за отображение конкретно заметок или тудушек, он отвечает за отображение n-ного количества любых элементов. Это не готовый кусок логики приложения, ему еще нужно получить эти элементы извне, они могут быть разными, соответственно помести его в ui

2021-04-05 15:39 UTC, ikorol3107 commented on practice/my-diary/site/app/src/App.tsx
> +      <Header name='Irina Korol' text='5 posts 4 liked' />
то есть header должен остаться в components ?

2021-04-05 15:40 UTC, TFK70 commented on practice/my-diary/site/app/src/App.tsx
> +      <Header name='Irina Korol' text='5 posts 4 liked' />
@ikorol3107 учитывая те изменения которые я запросил - да

2021-04-05 15:50 UTC, ikorol3107 commented on practice/my-diary/ui/item/src/Item.tsx
>  export const Item = styled.li(
Если item будет находиться в листе и , например, в дальнейшем потребуется создать другой список  - мне там повторно придется item прописывать?

2021-04-06 08:58 UTC, TFK70 requested changes

2021-04-06 08:58 UTC, TFK70 commented on practice/my-diary/site/app/src/App.tsx
> +      <MainPageHeader />
Пакет называется `@components/header`,а компонент `MainPageHeader`?

2021-04-06 08:58 UTC, TFK70 commented on practice/my-diary/components/header/src/MainPageHeader.tsx
> +        Irina Korol
intl?

2021-04-06 08:58 UTC, TFK70 commented on practice/my-diary/components/header/src/MainPageHeader.tsx
> +        5 posts 4 liked
почему 5 и 4 - константы? у тебя же не всегда будет 5 постов из которых 4 лайкнуты
вынеси их в переменные, здесь тоже не забудь пробросить текст через intl

2021-04-06 08:58 UTC, TFK70 commented on practice/my-diary/ui/list/src/List.tsx
> +const Item = styled.li(
на каждый компонент создавай свой файл, а то очень жирно все получается

2021-04-06 08:58 UTC, TFK70 commented on practice/my-diary/site/app/src/App.tsx
> +        <Text lineHeight='40px'>Запись</Text>
Не нужно описывать все эти страшные конструкции тут
Использование листа:
```javascript
<List items={{ ... }} />
```

2021-04-06 08:58 UTC, TFK70 commented on practice/my-diary/site/app/src/App.tsx
>          <Input width='100%' placeholder='Search by records' />
Вообще весь текст должен быть проброшен через intl

2021-04-08 16:57 UTC, TFK70 requested changes

2021-04-08 16:57 UTC, TFK70 commented on practice/my-diary/components/mainPageHeader/package.json
> +  "name": "@components/mainPageHeader",
main-page-header

2021-04-08 16:57 UTC, TFK70 commented on practice/my-diary/components/mainPageHeader/src/MainPageHeader.tsx
> +  <Box justifyContent='space-between' alignItems='flex-end' display='flex'>
display: flex есть в дефолт пропсах лейаута

2021-04-08 16:57 UTC, TFK70 commented on practice/my-diary/site/app/src/App.tsx
> +  const messages = {
А чего тут смешалось-то все на свете?)
Для месседжей - отдельный файл, как и везде

2021-04-08 16:57 UTC, TFK70 commented on practice/my-diary/site/app/src/App.tsx
> +  const postsSum = () => {
Как раз это и должно быть внутри хедера
Его использование:
```javascript
<MainPageHeader />
```

2021-04-08 16:57 UTC, TFK70 commented on practice/my-diary/ui/list/src/List.tsx
>    const elements = notes.map(item => {
Тут нету необходимости в переменной, можно сразу возвращать jsx

2021-04-08 16:57 UTC, TFK70 commented on practice/my-diary/components/mainPageHeader/src/messages.ts
> +    id: 'name',
id у месседжей должен быть чуть-чуть другой
Нужно взять название пакета к которому относятся месседжи:
```javascript
import { name } from '../package.json'

export default defineMessages({
   name: {
     id: `${name}.name`
     message: '...'
}
})
```

Если в id слов несколько - они разделяются андерскором: `${id}.full_name`

2021-04-08 16:57 UTC, TFK70 commented on practice/my-diary/site/app/src/App.tsx
>      { note: 'Flight to Moscow', important: false, id: 1 },
Кстати это тоже нужно через intl оформить

2021-04-11 10:24 UTC, ikorol3107 commented on practice/my-diary/site/app/src/App.tsx
>      { note: 'Flight to Moscow', important: false, id: 1 },
эти note будут удаляться, добавляться. Их можно будет динамически менять, если будут находиться в файле messages.ts ?

2021-04-12 04:46 UTC, TFK70 commented on practice/my-diary/site/app/src/App.tsx
>      { note: 'Flight to Moscow', important: false, id: 1 },
> эти note будут удаляться, добавляться. Их можно будет динамически менять, если будут находиться в файле messages.ts ?

В таком случае да, без интла

2021-04-12 07:51 UTC, TFK70 requested changes

2021-04-12 07:51 UTC, TFK70 commented on practice/my-diary/components/main-page-header/src/index.tsx
> +  return <MainPageHeader intl={intl} />
Это интересно, но useIntl хук можно(нужно) было использовать внутри самого хедера, в этой вложенности нет смысла

2021-04-12 07:51 UTC, TFK70 commented on practice/my-diary/ui/button/src/IconButton.tsx
> +    fontSize='17px'
У тебя здесь некоторые пропсы уже присутствуют в дефолт пропсах у кнопки, убери ненужные

2021-04-12 07:51 UTC, TFK70 commented on practice/my-diary/ui/list/src/List.tsx
>    const elements = notes.map(item => {
?

2021-04-12 10:44 UTC, TFK70 requested changes

2021-04-12 10:44 UTC, TFK70 commented on practice/my-diary/components/main-page-header/src/MainPageHeader.tsx
> +    // ... add logic late
Такие места помечай как TODO

```javascript
// TODO add logic later
```

В левом нижнем углу экрана в твоей IDE есть вкладка, которая отображает все места которые ты затудушила
![Снимок экрана 2021-04-12 в 15 40 49](https://user-images.githubusercontent.com/62806448/114382149-7765c700-9ba5-11eb-8588-cd5604ec1fcf.png)

Как видишь, это очень полезно когда тудушек становится слишком много

2021-04-12 12:54 UTC, TFK70 requested changes

2021-04-12 12:54 UTC, TFK70 commented on practice/my-diary/site/app/package.json
>      "@types/react-dom": "^17.0.1",
Все @types должны находиться в dev зависимостях
Проверь пожалуйста проект на такие места и исправь если найдутся

2021-04-12 13:09 UTC, ikorol3107 commented on practice/my-diary/site/app/package.json
>      "@types/react-dom": "^17.0.1",
проверила

2021-04-12 13:46 UTC, TFK70 approved these changes, later dismissed

2021-04-14 14:06 UTC, TFK70 requested changes

2021-04-14 14:06 UTC, TFK70 commented on practice/my-diary/components/main-page-header/src/MainPageHeader.tsx
> +import { Column, Row } from '../../../ui/layout/src/Layout'
Ого какой путь

2021-04-14 14:06 UTC, TFK70 commented on practice/my-diary/site/app/src/App.tsx
> +import { Column, Row }    from '../../../ui/layout/src/Layout'
Огоо какой путь

2021-04-14 14:06 UTC, TFK70 commented on practice/my-diary/components/main-page-header/src/MainPageHeader.tsx
> +      <Column width='none'>
А width none зачем?

2021-04-14 14:10 UTC, ikorol3107 commented on practice/my-diary/components/main-page-header/src/MainPageHeader.tsx
> +import { Column, Row } from '../../../ui/layout/src/Layout'
самой не нравится, но если пишу из компонента `@ui/layout` , то ругается, что "Module '"@ui/layout"' has no exported member 'Column'"

2021-04-14 14:23 UTC, ikorol3107 commented on practice/my-diary/components/main-page-header/src/MainPageHeader.tsx
> +      <Column width='none'>
потому-что мой хедер имеет justifyContent='space-between' , и если я оставлю дефолтный  width  = 100%  , то верстка поползет. Этого можно было избежать, добавив layout , но внутри <Text/> будут меняться значения и его ширина будет увеличиваться.

2021-04-14 15:00 UTC, TFK70 commented on practice/my-diary/components/main-page-header/src/MainPageHeader.tsx
> +import { Column, Row } from '../../../ui/layout/src/Layout'
Ну потому что такого у тебя действительно нет

Ты же из файла Layout только Layout и экспортируешь, хотя там не только он

Вообще лучше писать так
```javascript
export * from './Layout'
```

Так он вытянет из файла сразу все именованные экспорты

2021-04-14 19:42 UTC, TFK70 requested changes

2021-04-14 19:42 UTC, TFK70 commented on practice/my-diary/ui/layout/src/Box.tsx
> +  margin: '0 auto',
Подобного в ui компонентах вообще не должно быть

Наличие маржина подразумевает что твой компонент будет влиять на окружающую среду, ты его куда-то запихнешь и у тебя появится какой-то отступ непонятный

Это выходит за зону ответственности ui компонентов, ну и вообще маржины не надо уже использовать исходя из того что вы с созвона узнали

2021-04-14 19:42 UTC, TFK70 commented on practice/my-diary/ui/input/src/Input.tsx
>    margin: '0 2px 0 0',
Тоже

Везде убери подобное, все отступы регулируются за компонентом, но никак не в нем

2021-04-14 19:42 UTC, TFK70 commented on practice/my-diary/ui/layout/src/index.ts
>  export { Box } from './Box'
Лучше везде перепиши со звездочкой чтобы одного стиля придерживаться

2021-04-15 10:12 UTC, TFK70 requested changes

2021-04-15 10:12 UTC, TFK70 commented on practice/my-diary/components/main-page-header/src/MainPageHeader.tsx
> +          {likesSum()} {intl.formatMessage(messages.post)} {postsSum()}{' '}
Этот пробел (и подобные если есть) нужно убрать

2021-04-15 11:21 UTC, TFK70 requested changes

2021-04-15 11:21 UTC, TFK70 commented on practice/my-diary/components/main-page-header/src/MainPageHeader.tsx
> +      <Column width='none'>
Попробуй засунуть Column в Box
width none так себе выглядит

2021-04-15 14:33 UTC, TFK70 requested changes

2021-04-15 14:33 UTC, TFK70 commented on practice/my-diary/ui/text/src/Space.tsx
> +  for (let i = 1; i < count; i += 1) {
вместо for лучше использовать методы строк

2021-04-15 14:33 UTC, TFK70 commented on practice/my-diary/ui/text/src/Space.tsx
> +import { Text } from '@ui/text'
точно есть смысл тянуть Text?
стилизовать пробел нам вроде не надо)

2021-04-15 14:33 UTC, TFK70 commented on practice/my-diary/ui/text/src/Space.tsx
> +  let spaceLength = '\u00A0'
и да, снова лишняя переменная, можно и без нее

2021-04-15 14:33 UTC, TFK70 commented on practice/my-diary/components/main-page-header/src/MainPageHeader.tsx
> +            {likesSum()} {intl.formatMessage(messages.post)} {postsSum()}
тут тоже так-то пробелы есть)

2021-04-15 15:15 UTC, ikorol3107 commented on practice/my-diary/ui/text/src/Space.tsx
> +  for (let i = 1; i < count; i += 1) {
> вместо for лучше использовать методы строк

@TFK70 тут хорошо подходит String.prototype.repeat()  , но про него написано , что это экспериментальное API и не должно использоваться в рабочем коде. Могу я его использовать в учебном проекте ?

2021-04-15 15:25 UTC, TFK70 commented on practice/my-diary/ui/text/src/Space.tsx
> +  for (let i = 1; i < count; i += 1) {
@ikorol3107 
1. да, используй repeat
2. где такое написано?

2021-04-15 15:29 UTC, ikorol3107 commented on practice/my-diary/ui/text/src/Space.tsx
> +  for (let i = 1; i < count; i += 1) {
@TFK70 
1. ok
2. тут в списке методов: https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/String

2021-04-15 15:43 UTC, TFK70 requested changes

2021-04-15 15:43 UTC, TFK70 commented on practice/my-diary/ui/text/src/Space.tsx
> +  return <span>{'\u00A0'.repeat(count)}</span>
осталось только {} и return убрать

2021-04-15 15:46 UTC, TFK70 commented on practice/my-diary/ui/text/src/Space.tsx
> +  for (let i = 1; i < count; i += 1) {
@ikorol3107 по-моему с ним все более-менее ок
![Снимок экрана 2021-04-15 в 20 45 52](https://user-images.githubusercontent.com/62806448/114898492-92e20380-9e2b-11eb-969b-e8c57b26f7c8.png)

2021-04-15 17:04 UTC, TFK70 requested changes

2021-04-15 17:04 UTC, TFK70 commented on practice/my-diary/site/app/src/App.tsx
> +            All
а почему тут не через intl?

2021-04-15 17:04 UTC, TFK70 commented on practice/my-diary/site/app/src/App.tsx
> +            Liked
и тут

2021-04-15 17:04 UTC, TFK70 commented on practice/my-diary/site/app/src/App.tsx
> +          <Button backgroundColor='transparent'>Add</Button>
и тут

2021-04-15 17:31 UTC, TFK70 requested changes

2021-04-15 17:31 UTC, TFK70 commented on practice/my-diary/site/app/src/messages.ts
> +  like: {
liked же
like - что-то типа к побуждения к действию
liked - уже состояние

2021-04-16 03:26 UTC, TFK70 approved these changes

2021-04-16 13:55 UTC, TorinAsakura approved these changes
Поздравляю Ирина

2021-04-16 13:55 UTC, merged