feat(my-diary): add ability to delete items
Atlantis-Academy/frontend-study-ikorol pull request #70
Opened 2021-04-17 09:46 UTC by ikorol3107

affects: @practice/my-diary, @site/app, @ui/button, @ui/list

ISSUES CLOSED: #68

2021-04-17 09:58 UTC, TFK70 requested changes

2021-04-17 09:58 UTC, TFK70 commented on practice/my-diary/site/app/src/App.tsx
> +    Math.floor((1 + Math.random()) * 0x10000)
1. uniqueKey*
2. Я бы на твоем месте генерировал уникальный id на основе Date.now(), так больше шанс избежать коллизий + компутер считает не так много

2021-04-17 09:58 UTC, TFK70 commented on practice/my-diary/site/app/src/App.tsx
Лучше все функции, которые тут описаны, вынести в директорию actions
Локально, это даже не должно быть полноценным пакетом, просто будешь брать все оттуда:
```javascript
import { toggleStatus } from './actions'
```

2021-04-17 17:45 UTC, TFK70 requested changes

2021-04-17 17:45 UTC, TFK70 commented on practice/my-diary/site/app/src/App.tsx
> +  const { notes, toggleStatus, deleteItem } = actions([])
нихт, немножко не так

actions - директория, где каждая твоя функция(action) является отдельным модулем, импорт
```javascript
import { toggleStatus } from './actions'
```
возможен потому что в директории actions есть index, который все эти экшены наружу и экспортирует

2021-04-17 17:45 UTC, TFK70 commented on practice/my-diary/site/app/src/actions.ts
> +  const uniqueKey = () => Math.random() * Date.now()
Не понимаю к чему тут Math.random(). Если я правильно все понял, то тебе нужно дать тудушкам уникальные значения. Простой Date.now() для этого должно быть достаточно, если нет каких-то дополнительных требований к формату ключа

2021-04-17 17:45 UTC, TFK70 commented on practice/my-diary/site/app/src/actions.ts
> +    toggleStatus: (id, value) => {
Собственно, это и должно быть вынесено в разные файлы

Плюс эта функция должна быть [чистой](https://habr.com/ru/post/437512/)

2021-04-18 06:26 UTC, ikorol3107 commented on practice/my-diary/site/app/src/actions.ts
> +  const uniqueKey = () => Math.random() * Date.now()
@TFK70 потому-что если оставлять только Math.random(), то в консоли появляются предупреждения: Encountered two children with the same key

2021-04-18 06:32 UTC, TFK70 commented on practice/my-diary/site/app/src/actions.ts
> +  const uniqueKey = () => Math.random() * Date.now()
@ikorol3107 даа, это потому что начальные тудушки создаются одновременно и Date.now() тоже будет один
оставь пока так тогда

2021-04-18 07:36 UTC, ikorol3107 commented on practice/my-diary/site/app/src/App.tsx
> +  const { notes, toggleStatus, deleteItem } = actions([])
@TFK70 у меня в этих функциях используются хуки, и когда я пытаюсь делать как ты пишешь, то возникает ошибка:
Error: Invalid hook call. Hooks can only be called inside of the body of a function component. Не догоняю как ее избежать

2021-04-18 07:39 UTC, TFK70 commented on practice/my-diary/site/app/src/App.tsx
> +  const { notes, toggleStatus, deleteItem } = actions([])
@ikorol3107 у тебя в них не должен useState вызываться
это - хелперы, ты используешь useState внутри компонента, а эти функции для того чтобы произвести какие-то преобразования с состоянием
```javascript
setState(removeItem(state, id))
```
т.е. они принимают в себя старый стор и возвращают новый, который остается только присвоить чтобы произошел ререндер

2021-04-19 20:33 UTC, ikorol3107 commented on practice/my-diary/site/app/src/actions.ts
> +    toggleStatus: (id, value) => {
@TFK70 а я могу свои notes в реакт-контекст вынести? Они мне кроме Листа еще в хэдере же будут нужны.

2021-04-20 02:20 UTC, TFK70 commented on practice/my-diary/site/app/src/actions.ts
> +    toggleStatus: (id, value) => {
> @TFK70 а я могу свои notes в реакт-контекст вынести? Они мне кроме Листа еще в хэдере же будут нужны. 

Почему нет?

2021-04-20 09:59 UTC, TFK70 requested changes

2021-04-20 09:59 UTC, TFK70 commented on practice/my-diary/app/src/App.tsx
> +        <NotesProvider value={[notes, setNotes]}>
Ну так конечно тоже будет работать, но ты могла обернуть сразу все приложение в провайдер, вместо того чтобы заморачиваться с отдельными компонентами

2021-04-20 09:59 UTC, TFK70 commented on practice/my-diary/store/notes/src/index.ts
> +export { Provider as NotesProvider, Context as NotesContext } from './Context'
А зачем тебе Context экспортировать?

2021-04-20 09:59 UTC, TFK70 commented on practice/my-diary/app/src/App.tsx
>  export const App = () => {
И строчкой выше ^ ты так и не вынесла actions как следует

1. Сложи их в одноимённую директорию
2. Вынеси каждую функцию в свой файл

2021-04-20 13:54 UTC, TFK70 requested changes

2021-04-20 13:54 UTC, TFK70 commented on practice/my-diary/app/src/App.tsx
> +import { deleteItem }               from './actions'
Дубль

2021-04-20 13:54 UTC, TFK70 commented on practice/my-diary/store/notes/src/index.ts
> +export { Provider as NotesProvider } from './Context'
Правильно что ты хотела экспортировать что-то помимо провайдера,  но неправильно что ты экспортировала Context. У тебя же еще одна сущность есть помимо контекста и провайдера

Кстати, если до сих пор есть проблемы с пониманием контекста (например, зачем консьюмеры нужны - [почитай](https://ru.reactjs.org/docs/context.html#contextconsumer) или задай вопрос, это важная тема)

2021-04-21 10:05 UTC, TFK70 requested changes

2021-04-21 10:05 UTC, TFK70 commented on practice/my-diary/app/src/App.tsx
> +          <List deleteItem={deleteItem} toggleStatus={toggleStatus} />
Дай угадаю: если этот лист положить в Row - то верстка внутри самого листа поедет?)

2021-04-21 10:05 UTC, TFK70 commented on practice/my-diary/ui/list/src/List.tsx
>      return (
Во-первых тут опять return ненужный

2021-04-21 10:05 UTC, TFK70 commented on practice/my-diary/ui/list/src/List.tsx
> +      <Column key={item.id}>
А во-вторых, ну, ты же понимаешь что этот Column будет создаваться на каждый элемент списка?

2021-04-21 10:41 UTC, ikorol3107 commented on practice/my-diary/app/src/App.tsx
> +          <List deleteItem={deleteItem} toggleStatus={toggleStatus} />
@TFK70 да) А почему здесь лист нужно в Row класть?

2021-04-21 10:53 UTC, TFK70 commented on practice/my-diary/app/src/App.tsx
> +          <List deleteItem={deleteItem} toggleStatus={toggleStatus} />
@ikorol3107 тебе в листе нужно расположить компоненты вертикально => они должны находиться внутри Column

Сейчас они располагаются вертикально потому что у родительского для листа враппера `flex-direction: column`. Когда ты меняешь его на Row - flex-direction меняется вместе с ним и элементы внутри листа располагаются уже горизонтально => для листа должен быть свой враппер с `flex-direction: column`(он же просто Column)
В коде это ±так:
```javascript
<Column>
   <Element />
   <Layout flexBasis={7} />
   <Element />
... 
</Column>
```

Сейчас ты создаешь свой Column на каждой итерации:
```javascript
<Column>
   <Element />
</Column>
<Layout flexBasis={7} />
<Column>
   <Element />
</Column>
```

2021-04-21 12:03 UTC, ikorol3107 commented on practice/my-diary/ui/list/src/List.tsx
> +      <Column key={item.id}>
@TFK70 блин реально чушь написала какую-то. Тогда следуя логике каждый элемент списка - это Row плюс Layout , но во что их обернуть тогда? Родительский элемент то один должен быть

2021-04-21 12:05 UTC, TFK70 commented on practice/my-diary/ui/list/src/List.tsx
> +      <Column key={item.id}>
@ikorol3107 дай тогда тут примерные наброски кода как хочешь сделать, я скорректирую

2021-04-21 12:08 UTC, ikorol3107 commented on practice/my-diary/ui/list/src/List.tsx
> +      <Column key={item.id}>
> @ikorol3107 дай тогда тут примерные наброски кода как хочешь сделать, я скорректирую

 ок, сейчас. как тут в комментах кусок кода вставить?

2021-04-21 12:09 UTC, TFK70 commented on practice/my-diary/ui/list/src/List.tsx
> +      <Column key={item.id}>
> > @ikorol3107 дай тогда тут примерные наброски кода как хочешь сделать, я скорректирую
> 
> ок, сейчас. как тут в комментах кусок кода вставить?

+

2021-04-21 12:15 UTC, ikorol3107 commented on practice/my-diary/ui/list/src/List.tsx
> +      <Column key={item.id}>
`notes.map(item => (
<Row key={item.id}>
          <Item />
          <Button/>
</Row>
<Layout flexBasis={6} />
))`

2021-04-21 12:19 UTC, TFK70 commented on practice/my-diary/ui/list/src/List.tsx
> +      <Column key={item.id}>
@ikorol3107 распиши цель, что должно быть в итоге

И еще для вставки кода лучше использовать это чтобы подсветка крутая была:
\```javascript
Твой код
\```

2021-04-21 12:26 UTC, ikorol3107 commented on practice/my-diary/ui/list/src/List.tsx
> +      <Column key={item.id}>
В итоге Лист должен находиться в одной колонке, а каждый элемент списка должен быть обернут в Row ,
но чтоб разделить элементы , в элемент должен быть включен лэйаут:
```javascript
export const List: any = ({ deleteItem, toggleStatus }) => {
  const [notes, setNotes] = useNotes()
  return notes.map(item => (
    <>
        <Row key={item.id}>
          <Item/>
       </Row>
       <Layout flexBasis={6} />
    </>
```

2021-04-21 12:42 UTC, ikorol3107 commented on practice/my-diary/ui/list/src/List.tsx
> +      <Column key={item.id}>
@TFK70 может так?:
```javascript
export const List: any = ({ deleteItem, toggleStatus }) => {
  const [notes, setNotes] = useNotes()
  return notes.map(item => (
    <Box display='contents'>
        <Row key={item.id}>
          <Item/>
          ....
       </Row>
       <Layout flexBasis={6} />
    </Box>
```

2021-04-21 12:53 UTC, TFK70 commented on practice/my-diary/ui/list/src/List.tsx
> +      <Column key={item.id}>
> @TFK70 может так?:
> ```javascript
> export const List: any = ({ deleteItem, toggleStatus }) => {
>   const [notes, setNotes] = useNotes()
>   return notes.map(item => (
>     <Box display='contents'>
>         <Row key={item.id}>
>           <Item/>
>           ....
>        </Row>
>        <Layout flexBasis={6} />
>     </Box>
> ```

Но ты же можешь писать выражения прямо внутри jsx:
```javascript
<Column>
   {notes.map(note => <Jsx />)}
</Column>
```

2021-04-21 13:23 UTC, ikorol3107 commented on practice/my-diary/ui/list/src/List.tsx
> +      <Column key={item.id}>
@TFK70 , могу, но что мне это даст? Вот такой результат ты имеешь в виду?

```javascript
export const List: any = ({ deleteItem, toggleStatus }) => {
  const [notes, setNotes] = useNotes()

return <Column>
  {notes.map(item => (
    <Row key={item.id}>
      <Item >
      ...
    </Row>
    <Layout flexBasis={6} />
    )
    )}
  </Column>
}
```

2021-04-21 15:46 UTC, TFK70 commented on practice/my-diary/ui/list/src/List.tsx
> +      <Column key={item.id}>
> @TFK70 , могу, но что мне это даст? Вот такой результат ты имеешь в виду?
> 
> ```javascript
> export const List: any = ({ deleteItem, toggleStatus }) => {
>   const [notes, setNotes] = useNotes()
> 
> return <Column>
>   {notes.map(item => (
>     <Row key={item.id}>
>       <Item >
>       ...
>     </Row>
>     <Layout flexBasis={6} />
>     )
>     )}
>   </Column>
> }
> ```

Ну примерно такой, да
Распиши тогда что произойдет если ты так напишешь

2021-04-21 18:28 UTC, ikorol3107 commented on practice/my-diary/ui/list/src/List.tsx
> +      <Column key={item.id}>
@TFK70 если так, то всё, что тут в скобках:
```javascript
item => (......) 
```
подчёркивает красным с просьбой сделать один родительский элемент

2021-04-21 19:06 UTC, TFK70 commented on practice/my-diary/ui/list/src/List.tsx
> +      <Column key={item.id}>
@ikorol3107 
1. Я ж не говорил что что-то неправильно и т.д., просто распиши что будет если запихнуть все в Column
2. В случае неясных ошибок - лог+код, иначе я физически помочь не смогу

2021-04-22 06:50 UTC, ikorol3107 commented on practice/my-diary/ui/list/src/List.tsx
> +      <Column key={item.id}>
@TFK70 
расписываю:
код не компилируется. Ошибка "Adjacent JSX elements must be wrapped in an enclosing tag. Did you want a JSX fragment <>...</>?"

2021-04-22 06:51 UTC, TFK70 commented on practice/my-diary/ui/list/src/List.tsx
> +      <Column key={item.id}>
> @TFK70 
> расписываю:
> код не компилируется. Ошибка "Adjacent JSX elements must be wrapped in an enclosing tag. Did you want a JSX fragment <>...</>?"

А код?

2021-04-22 07:23 UTC, ikorol3107 commented on practice/my-diary/ui/list/src/List.tsx
> +      <Column key={item.id}>
```javascript
export const List: any = ({ deleteItem, toggleStatus }) => {
  const [notes, setNotes] = useNotes()

return 
  <Column>
  {notes.map(item => (
    <Row key={item.id}>
      <Item >
      ...
    </Row>
    <Layout flexBasis={6} />
    )
    )}
  </Column>
}
```

2021-04-22 07:46 UTC, TFK70 commented on practice/my-diary/ui/list/src/List.tsx
> +      <Column key={item.id}>
@ikorol3107 ну когда ты возвращаешь jsx он действительно должен быть обёрнут в какой-то один компонент
Если у этого компонента не должно быть какого-то функционала - можно обернуть всё в <></>

2021-04-22 11:08 UTC, ikorol3107 commented on practice/my-diary/ui/list/src/List.tsx
> +      <Column key={item.id}>
@TFK70 а знаешь, что не так, когда я всё в <></> оборачиваю? Получается, что теперь каждый note без уникального ключа... Значит такое решение здесь нельзя оставлять.

2021-04-22 11:10 UTC, TFK70 commented on practice/my-diary/ui/list/src/List.tsx
> +      <Column key={item.id}>
@ikorol3107 
```javascript
<div key={id}>
</div>
```

2021-04-22 11:15 UTC, TFK70 commented on practice/my-diary/ui/list/src/List.tsx
> +      <Column key={item.id}>
@ikorol3107 но на самом деле можно сделать проще и красивее
```javascript
<Row>
...
</Row>
<Layout />
```
^ Это вынеси в Item
И сделай так:
```javascript
{items.map(item => <Item key={item.id} value={item.title} />)}
```

2021-04-22 11:19 UTC, TFK70 commented on practice/my-diary/ui/list/src/List.tsx
> +      <Column key={item.id}>
@ikorol3107 ну и у тебя почему-то Item - это просто обёртка, и в таком случае не понятно зачем было его в отдельный компонент выносить, когда он эквивалентен Box

Его нужно сделать пожирнее, Item должен отвечать за отображение данных о конкретном айтеме, т. е. полноценный Row, как я и описал выше

2021-04-23 10:01 UTC, TFK70 requested changes

2021-04-23 10:01 UTC, TFK70 commented on practice/my-diary/ui/list/src/Item.tsx
> +  ({ ...props }) => ({
1. ({....props }) === (props)
2. Зачем их тут описывать если они нигде не используются?

2021-04-23 17:56 UTC, TFK70 approved these changes

2021-04-23 19:06 UTC, TFK70 requested changes

2021-04-23 19:06 UTC, TFK70 commented on package.json
> +    "@atlantis-lab/tsconfig": "^0.1.12",
@atlantis-lab/config

2021-04-23 19:12 UTC, TorinAsakura approved these changes

2021-04-23 19:13 UTC, TorinAsakura commented on package.json
> +    "@atlantis-lab/tsconfig": "^0.1.12",
зачем? при импорте actl все конфиги уже есть, зачем вы вообще это делаете?

2021-04-23 19:14 UTC, TFK70 approved these changes

2021-04-23 19:14 UTC, merged