feat(my-diary): add functionality for adding new notes
Atlantis-Academy/frontend-study-ikorol pull request #71
Opened 2021-04-24 08:40 UTC by ikorol3107

affects: @my-diary/app, @practice/my-diary

ISSUES CLOSED: #69

2021-04-24 10:29 UTC, TorinAsakura requested changes

2021-04-24 10:29 UTC, TorinAsakura commented on practice/my-diary/app/src/App.tsx
> +              type='button'
а у тебя кнопка может быть не…кнопкой?

2021-04-24 15:36 UTC, TorinAsakura requested changes

2021-04-24 15:36 UTC, TorinAsakura commented on practice/my-diary/app/src/App.tsx
> +              padding='0 6px'
у тебя есть случаи где паддинги иные? если нет - тогда зачем ты определяешь их при импорте?

2021-04-25 10:46 UTC, TFK70 approved these changes

2021-04-25 20:09 UTC, TorinAsakura approved these changes

2021-04-25 20:09 UTC, merged