refactor(my-diary): add theme to project
Atlantis-Academy/frontend-study-ikorol pull request #79
Opened 2021-05-03 05:28 UTC by ikorol3107

affects: @my-diary/app, @components/main-page-header, @practice/my-diary, @ui/list, @ui/theme

ISSUES CLOSED: #76

2021-05-03 06:20 UTC, TFK70 requested changes

2021-05-03 06:20 UTC, TFK70 commented on practice/my-diary/components/main-page-header/src/MainPageHeader.tsx
> +import { theme }                    from '@ui/theme'
А провайдер тогда зачем?
Тема должна использоваться так же, как и любое другое значение из контекста: с помощью хука или консьюмера, тогда и лишние импорты с зависимостями будут не нужны

2021-05-03 06:20 UTC, TFK70 commented on practice/my-diary/components/main-page-header/src/MainPageHeader.tsx
> +      <Text fontSize={theme.fontSizes.large} fontWeight='bold'>
А вот в этом, кстати, нет необходимости. styled-system крутой и делает это за тебя, т.е. ты можешь просто написать fontSize='large' и готово

2021-05-03 06:20 UTC, TFK70 commented on practice/my-diary/components/main-page-header/src/MainPageHeader.tsx
> +      <Text fontSize={theme.fontSizes.large} fontWeight='bold'>
И тогда тебе здесь объект с темой не нужен соовсем, т.к. компонент использует ее внутри себя

2021-05-03 06:20 UTC, TFK70 commented on practice/my-diary/ui/theme/src/theme.ts
> +  fontSizes: {
Объект будет получаться оочень большим, так что каждую проперти лучше держать в отдельном файле, для чистоты (colors.ts  и тд), так будет намного проще в ней ориентироваться

2021-05-04 08:13 UTC, ikorol3107 commented
@TFK70 посмотри, пожалуйста, Item: не могу понять почему везде theme работает корректно, а в Item - нет.

2021-05-04 08:14 UTC, TFK70 commented
@ikorol3107 посмотрю, сейчас переключайся на gh pages

2021-05-04 08:19 UTC, TFK70 requested changes

2021-05-04 08:19 UTC, TFK70 commented on practice/my-diary/ui/list/src/Item.tsx
> +    borderRadius: 'normal',
Раньше это работало потому что эти пропсы шли в коллбэки от styled-system, которые под капотом обращаются в тему и берут значения оттуда. Здесь styled-system уже нет, так что эту логику нужно описать [самостоятельно](https://emotion.sh/docs/theming) (секция styled)

2021-05-04 16:12 UTC, ikorol3107 commented on practice/my-diary/ui/list/src/Item.tsx
> +    borderRadius: 'normal',
@TFK70 Ок, сделала. Все отрабатывает корректно теперь в Item кроме StarIcon, тк этот ui-компонент получает пропсы . Я не могу понять как тут поступить

2021-05-04 16:14 UTC, TFK70 commented on practice/my-diary/ui/list/src/Item.tsx
> +    borderRadius: 'normal',
@ikorol3107 подробнее
код, ошибка, что должно быть в итоге

2021-05-04 16:27 UTC, ikorol3107 commented on practice/my-diary/ui/list/src/Item.tsx
> +    borderRadius: 'normal',
@TFK70 ошибки нет, просто вместо моего желтого цвета из theme, StarIcon присваивается стандартный желтый

2021-05-04 16:30 UTC, TFK70 commented on practice/my-diary/ui/list/src/Item.tsx
> +    borderRadius: 'normal',
@ikorol3107 вообще цвет звезды тогда уж должен быть по дефолту жёлтым, но в твоем случае можно просто hex значение захардкодить, в проекте не предусмотрено функционала темизации пропов иконок

2021-05-04 16:31 UTC, ikorol3107 commented on practice/my-diary/ui/list/src/Item.tsx
> +    borderRadius: 'normal',
```javascript
<Row>
      <StyledItem onDoubleClick={() => setNotes(toggleStatus(notes, note.id, 'liked'))} backgroundColor='white' borderRadius='normal'>
        <Text lineHeight='40px' padding='0 6px'>
          {note.note}
        </Text>
      </StyledItem>
      <Layout flexBasis={3} />
      <Box>
        <Button
          backgroundColor='white'
          border='none'
          width='40px'
          onClick={() => setNotes(toggleStatus(notes, note.id, 'important'))}
        >
          <StarIcon color={note.important ? 'yellow' : 'gray'} />
        </Button>
        <Layout flexBasis={3} />
        <Button
          backgroundColor='white'
          border='none'
          width='40px'
          onClick={() => setNotes(deleteItem(notes, note.id))}
        >
          <TrashIcon />
        </Button>
        <Layout flexBasis={3} />
        <Button backgroundColor='white' border='none' width='40px'>
          <HeartIcon opacity={note.liked ? '1' : '0'} />
        </Button>
      </Box>
    </Row>
```

2021-05-04 17:00 UTC, TFK70 requested changes

2021-05-04 17:00 UTC, TFK70 commented on practice/my-diary/app/src/App.tsx
> +            <Box margin='auto' justifyContent='center' backgroundColor='#eaf5fc'>
Цвет захардкоженный

2021-05-04 17:10 UTC, TFK70 approved these changes

2021-05-04 17:11 UTC, TorinAsakura approved these changes

2021-05-04 17:11 UTC, merged