feat(objects): add a lesson about objects and OOPs concepts
Atlantis-Academy/frontend-study-ikorol pull request #8
Opened 2020-12-05 19:21 UTC by ikorol3107

ISSUES CLOSED: #7

2020-12-05 19:23 UTC, TorinAsakura requested changes

2020-12-05 19:23 UTC, TorinAsakura commented on lessons/objects/README.md
> +- Метод `toggleVisibleMyDB` проверяет свойство `privat`. Если оно `false` - переключает его в `true` и наоборот
что за свойство privat? Я знаю private
Проверь

2020-12-07 09:34 UTC, ikorol3107 commented on lessons/objects/README.md
> +- Метод `toggleVisibleMyDB` проверяет свойство `privat`. Если оно `false` - переключает его в `true` и наоборот
Да, мой косяк. У автора курса так названа переменная и меня это не смутило, т.к. привыкла на немецком видеть именно такое написание, а по английски это действительно должно быть private . Сейчас исправлю

2020-12-07 12:53 UTC, TorinAsakura approved these changes

2020-12-07 12:53 UTC, merged