fix: add checkout steps to workflow
Atlantis-Academy/frontend-study-ikorol pull request #88
Opened 2021-05-05 09:52 UTC by ikorol3107

ISSUES CLOSED: #86

2021-05-05 09:55 UTC, TFK70 approved these changes

2021-05-05 11:36 UTC, TFK70 requested changes

2021-05-05 11:36 UTC, TFK70 commented on .github/workflows/deploy.yml
>      steps:
https://github.com/atls-academy/frontend-study-gochicus/pull/79#discussion_r626481075

2021-05-05 14:08 UTC, ikorol3107 commented on .github/workflows/deploy.yml
>      steps:
@TFK70 речь идет о всех зависимостях от экшенов или те, что добавились у Саши? У меня yarn.lock не изменялся в последих ПР. Сейчас там три зависимости: "@actions/core@1.2.0" , "@actions/core@1.2.6" , "@actions/github@1.1.0". Их оставлять?

2021-05-05 14:12 UTC, TFK70 commented on .github/workflows/deploy.yml
>      steps:
@ikorol3107 вообще никакие изменения связанные с gh pages не должны подразумевать добавление каких-либо зависимостей т.к. это просто по сути добавление одного воркфлоу

Саша просто после того как лишнюю зависимость убрал локфайл не закоммитил

Тебе необходимо внести правки из комментов на которые я ссылался: добавить степы для проверки кода

2021-05-05 14:23 UTC, ikorol3107 commented on .github/workflows/deploy.yml
>      steps:
@TFK70 так у меня  изменения связанные с gh pages не добавляют никакие зависимости

2021-05-05 14:24 UTC, TFK70 commented on .github/workflows/deploy.yml
>      steps:
@ikorol3107 ну я и говорю, у тебя все нормально с ними

Нужны только доп. проверки

2021-05-05 14:25 UTC, ikorol3107 commented on .github/workflows/deploy.yml
>      steps:
@TFK70 так у меня изменения связанные с gh pages не добавляют никакие зависимости

2021-05-05 14:32 UTC, ikorol3107 commented on .github/workflows/deploy.yml
>      steps:
@TFK70 мы вроде только про эти проверки говорили:

```javascript
- name: Checkout
  uses: actions/checkout@v2
- name: Setup Node.js
  uses: actions/setup-node@v2
  with:
    node-version: '14'
```
Нужны какие-то еще?

2021-05-05 14:33 UTC, TFK70 commented on .github/workflows/deploy.yml
>      steps:
@ikorol3107 это не проверки

Это необходимо чтобы у тебя было корректно засетаплено окружение

Проверок тут как раз никаких нет

2021-05-05 14:58 UTC, ikorol3107 commented on .github/workflows/deploy.yml
>      steps:
@TFK70  Эти?
```javascript

      - name: Lint
        run: yarn lint

      - name: TypeCheck
        run: yarn typecheck

```

2021-05-05 19:40 UTC, TFK70 commented on .github/workflows/deploy.yml
>      steps:
@ikorol3107 да

2021-05-06 07:32 UTC, TFK70 approved these changes

2021-05-06 13:05 UTC, TFK70 requested changes

2021-05-06 13:05 UTC, TFK70 commented on .github/workflows/deploy.yml
> +      - name: Lint
Проверки здесь все-таки не нужны

И переименуй чеки в checks, а не codelinter

2021-05-06 16:06 UTC, ikorol3107 commented on .github/workflows/deploy.yml
> +      - name: Lint
@TFK70  о каких чеках ты говоришь, мой второй yml-файл? И еще вопрос все-таки про адрес репы. У меня он указан сейчас вот такой:
`"repository": "https://github.com/atls-academy/frontend-study-ikorol.github.io"`
я правильно понимаю, что он должен быть вот таким:
`https://frontend-study-ikorol.github.io/` ?

2021-05-06 16:13 UTC, TFK70 commented on .github/workflows/deploy.yml
> +      - name: Lint
@ikorol3107 
1. Про переименование - да, второй воркфлоу
2. [Тут](https://docs.github.com/en/pages/getting-started-with-github-pages/about-github-pages) есть параграф посвященный этому

2021-05-06 16:27 UTC, TFK70 requested changes

2021-05-06 16:27 UTC, TFK70 commented on practice/my-diary/package.json
> +  "repository": "https://frontend-study-ikorol.github.io",
На всякий случай [продублирую](https://docs.github.com/en/pages/getting-started-with-github-pages/about-github-pages) страницу где можно почитать по каким правилам строится ссылка, там даже примеры если что есть

2021-05-06 16:45 UTC, ikorol3107 commented on practice/my-diary/package.json
> +  "repository": "https://frontend-study-ikorol.github.io",
@TFK70 да, я ее прочитала. По логике здесь должен быть адрес:
 `https://frontend-study-ikorol.github.io/my-diary`
Но вот [тут](https://github.com/atls-academy/frontend-study-ikorol) Андрей в сайдбаре указывает другую ссылку.

2021-05-06 16:46 UTC, TFK70 commented on practice/my-diary/package.json
> +  "repository": "https://frontend-study-ikorol.github.io",
@ikorol3107 в сайдбаре ссылка ведущая на само приложение
тут нужно указать ссылку для репозитория, это другое

2021-05-06 16:47 UTC, TFK70 commented on practice/my-diary/package.json
> +  "repository": "https://frontend-study-ikorol.github.io",
> @TFK70 да, я ее прочитала. По логике здесь должен быть адрес:
> `https://frontend-study-ikorol.github.io/my-diary`
> Но вот [тут](https://github.com/atls-academy/frontend-study-ikorol) Андрей в сайдбаре указывает другую ссылку.

Тут скорее нужно верить документации, а не логике
Вот по документации тут соооовсем другой урл должен быть

2021-05-06 17:00 UTC, ikorol3107 commented on practice/my-diary/package.json
> +  "repository": "https://frontend-study-ikorol.github.io",
@TFK70  в документации указано: `http(s)://<organization>.github.io/<repository>`.
Значит мой адрес должен быть: `http(s)://atls-academy.github.io/frontend-study-ikorol` , так ?

2021-05-06 17:01 UTC, TFK70 commented on practice/my-diary/package.json
> +  "repository": "https://frontend-study-ikorol.github.io",
@ikorol3107 да

2021-05-06 17:31 UTC, TFK70 approved these changes

2021-05-06 17:40 UTC, TorinAsakura approved these changes

2021-05-06 17:40 UTC, merged