Feat/update app design
Atlantis-Academy/frontend-study-ikorol pull request #89
Opened 2021-05-12 11:04 UTC by ikorol3107

Update app design

2021-05-12 12:12 UTC, TFK70 requested changes
1. Это не drawer, а модалка
2. Слой с затемнением вылезает за пределы белого блока и залезает на кнопку добавления тудушки
3. У кнопки вызова меню (которая бургер-меню) должен быть `cursor: 'pointer'`, тк кликабельно
4. На тудушках тоже должен быть `cursor: 'pointer'` тк есть эвент при наведении
![Снимок экрана 2021-05-12 в 17 05 15](https://user-images.githubusercontent.com/62806448/117972179-3ac3f180-b344-11eb-8763-840bfc695c5a.png)

5. Почему синий фон только на пол-экрана?
![Снимок экрана 2021-05-12 в 17 10 40](https://user-images.githubusercontent.com/62806448/117972790-fd139880-b344-11eb-96ba-84ff719a0278.png)


Если что, drawer нужно делать за пределами основного блока с тудулистом, а черный слой должен затемнять всё твое приложение. Ну и, разумеется, он должен выдвигаться с анимацией

2021-05-13 11:22 UTC, ikorol3107 commented
@TFK70 не могу понять, почему не отрабатывает transition (transform работает корректно):
```javascript
...
const StyledDrawer = styled.div(
  system({
    transform: true,
    transition: true,
  }),
  () => ({
    position: 'fixed',
    top: '0',
    zIndex: 2,
    ...
  }),
  color,
  space,
)

export const Drawer = ({ onVisible, onClose, children }) => {
  return (
    <Box display={onVisible}>
      <Box
        onClick={onClose}
        position='absolute'
        top='0'
        left='0'
        width='100%'
        height='100%'
        backgroundColor='lightGray'
        zIndex={1}
      />
      <StyledDrawer
        transform={onVisible === 'flex' ? 'translateY(50%)' : 'translateY(0)'}
        transition='transform 1s'
      >
        {children}
      </StyledDrawer>
    </Box>
  )
}
```

2021-05-13 12:06 UTC, TFK70 commented
@ikorol3107 это потому что ты не даешь ему отработать. С самим transition все в порядке. transition сглаживает переход из одного состояния в другое, а тут этого перехода и нет, у тебя каждый раз при перерисовке меняется начальное состояние, а не мутирует предыдущее

В данном случае проще всего будет воспользоваться `@keyframes`. Самое главное - придерживаться текущего кодстайла. Реализовать нужно средствами styled, анимацию опиши прямо в StyledDrawer. Появление блока с затемнением тоже должно быть анимировано

Но у тебя сам drawer выглядит немного не как drawer. Взгляни еще [сюда](https://material-ui.com/ru/components/drawers/) для большей наглядности. Если он вертикальный - то занимает всю высоту, если горизонтальный - всю ширину

И drawer надо бы сделать все-таки вертикальным (выдвигается сбоку), так он не будет закрывать само приложение, что полезно во время выполнения поиска по тудушкам. И в мобильной версии такой будет намного привычнее.

2021-05-14 09:57 UTC, TFK70 requested changes

2021-05-14 09:57 UTC, TFK70 commented on practice/my-diary/components/post-controls/src/PostControls.tsx
>                backgroundColor='deepPurple'
Добавь стили для activeState в кнопках фильтров по аналогии с like и important

2021-05-14 11:06 UTC, TFK70 requested changes

2021-05-14 11:06 UTC, TFK70 commented on practice/my-diary/ui/drawer/src/Drawer.tsx
> +    '@keyframes container': {
Получилось хорошо, но с анимацией есть накладки

Конечный вариант должен выглядеть так:

https://user-images.githubusercontent.com/62806448/118261025-72f63c00-b4cc-11eb-84b2-1add79af7bbd.mov

Сейчас анимация срабатывает только в первый и единственный раз и нету анимации задвигания

Чтобы это реализовать тебе придется написать 2 анимации для каждого блока (или проигрывать одну и ту же в обратном порядке) и воспользоваться свойством `forwards` у `animation`, которое сохраняет все трансформации от анимации после ее выполнения (погугли)

2021-05-14 11:06 UTC, TFK70 commented on practice/my-diary/ui/drawer/src/Drawer.tsx
> +    '@keyframes drawer': {
И анимации лучше называть по факту их функционала, а не по контексту: `slideIn`, `slideOut`, `appear`,`disappear` и тд

2021-05-14 11:06 UTC, TFK70 commented on practice/my-diary/ui/drawer/src/Drawer.tsx
> +export const Drawer = ({ onVisible, onClose, children }) => {
префикс `on` используется только для коллбеков в эвентах

2021-05-14 11:06 UTC, TFK70 commented on practice/my-diary/ui/drawer/src/Drawer.tsx
> +    <Box display={onVisible}>
И переключать `flex` и `none` тогда уж нужно тут, а не снаружи

Но, возможно, от этого куска стоит вообще избавиться в силу правок предложенных выше ^

2021-05-14 11:06 UTC, TFK70 commented on practice/my-diary/ui/drawer/src/Drawer.tsx
> +      to: { backgroundColor: 'rgba(0,0,0,0.2)' },
К слову убирать блок тоже придется, чтобы приложение под ним оставалось кликабельным, но `display: none` работать не будет, поэтому обрати внимание на `visibility: 'visible'`/`visibility: 'hidden'`, он работает как `display: 'flex'/'none'` за исключением того, что `visibility: 'hidden'` не удаляет элемент из потока

2021-05-14 11:06 UTC, TFK70 commented on practice/my-diary/components/post-controls/src/PostControls.tsx
> +    <Drawer onVisible={showDrawer ? 'flex' : 'none'} onClose={() => setShowDrawer(false)}>
Ну и вот да, как я уже говорил подобную логику (`onVisible={showDrawer ? 'flex' : 'none'}`) нужно описывать внутри самих компонентов

2021-05-14 11:06 UTC, TFK70 commented on practice/my-diary/components/post-controls/src/PostControls.tsx
> +import { Space }               from '../../../ui/text/src/Space'
И путь кривой

2021-05-14 14:20 UTC, ikorol3107 commented on practice/my-diary/ui/drawer/src/Drawer.tsx
> +    '@keyframes container': {
@TFK70  я поняла логику, но не понимаю как связать запуск анимации со сменой свойства visibility.

2021-05-14 14:25 UTC, TFK70 commented on practice/my-diary/ui/drawer/src/Drawer.tsx
> +    '@keyframes container': {
@ikorol3107 ну тут все проще чем ты думаешь на самом деле)
Просто свяжи запуск конкретной анимации по названию в зависимости от visibility, это сработает тк компонент при смене visibility будет делать ререндер, а animation срабатывает как раз при маунте

2021-05-14 14:49 UTC, ikorol3107 commented on practice/my-diary/ui/drawer/src/Drawer.tsx
> +    '@keyframes container': {
@TFK70 я сделала так, и ничего не работает %-/ 
```javascript
export const Drawer = ({ visible, close, children }) => {
 return(
   <Box visibility={visible ? 'visible' : 'hidden'} >
   <StyledContainer onClick={close} animationName={visible ? 'appear' : 'disAppear'}/>
   <StyledDrawer animationName={visible ? 'slideIn' : 'slideOut'}>{children}</StyledDrawer>
 </Box>
```

2021-05-14 14:52 UTC, TFK70 commented on practice/my-diary/ui/drawer/src/Drawer.tsx
> +    '@keyframes container': {
@ikorol3107 я так понял он в этом случае просто без анимации появляется/исчезает?

2021-05-14 14:55 UTC, ikorol3107 commented on practice/my-diary/ui/drawer/src/Drawer.tsx
> +    '@keyframes container': {
@TFK70 да

2021-05-14 14:57 UTC, TFK70 commented on practice/my-diary/ui/drawer/src/Drawer.tsx
> +    '@keyframes container': {
@ikorol3107 потому что
```javascript
<Box visibility={visible ? 'visible' : 'hidden'} >
```

Он свой visibility меняет без всяких делеев и анимаций, так что твой drawer сначала исчезает, а потом проигрывает анимацию

2021-05-14 15:00 UTC, TFK70 commented on practice/my-diary/ui/drawer/src/Drawer.tsx
> +    '@keyframes container': {
@ikorol3107 немного подскажу: тебе же не обязательно помещать все в один блок у которого меняется visibility, ты можешь менять visibility у каждого блока по-отдельности, как раз под конец его анимации

2021-05-14 16:08 UTC, ikorol3107 commented on practice/my-diary/ui/drawer/src/Drawer.tsx
> +    '@keyframes container': {
@TFK70 не выходит каменный цветок... Cделала так:
```javascript
export const Drawer = ({ visible, close, children }) => {
 return(
   <Box >
   <StyledContainer onClick={close} 
        animationName={visible ? 'appear' : 'disAppear'} 
        visibility={visible ? 'visible' : 'hidden'}/>
   <StyledDrawer animationName={visible ? 'slideIn' : 'slideOut'} 
        visibility={visible ? 'visible' : 'hidden'}>{children}</StyledDrawer>
 </Box>
 )
```
добавила `transition: 'visibility .3s .3s'` , но я явно упускаю где-то логику...

2021-05-14 17:43 UTC, TFK70 requested changes

2021-05-14 17:43 UTC, TFK70 commented on practice/my-diary/ui/drawer/src/Drawer.tsx
> +    visibility: true,
Он тут уже не нужен

2021-05-14 17:43 UTC, TFK70 commented on practice/my-diary/ui/drawer/src/Drawer.tsx
> +    visibility: true,
И тут

2021-05-14 17:43 UTC, TFK70 commented on practice/my-diary/ui/drawer/src/Drawer.tsx
> +export const Drawer = ({ visible, close, children }) => {
onClose было корректным наименованием, это же событие

2021-05-14 17:43 UTC, TFK70 commented on practice/my-diary/app/src/App.tsx
> +  const [showDrawer, setShowDrawer] = useState(null)
Раз уж мы тут пришли к null (который является всеми типами сразу) - то этот useState точно нужно типизировать
`useState<boolean>(null)` ([typescript generics)](https://www.typescriptlang.org/docs/handbook/2/generics.html)

2021-05-14 17:43 UTC, TFK70 commented on practice/my-diary/components/post-controls/src/PostControls.tsx
> +    <Drawer visible={showDrawer} close={() => setShowDrawer(false)}>
Тк visible - это бул, то добавь префикс is у пропа: `isVisible`
Код будет более читабельным

2021-05-14 21:29 UTC, TFK70 requested changes

2021-05-14 21:29 UTC, TFK70 commented on practice/my-diary/ui/theme/src/radii.ts
> +  gigant: 35,
giant*

2021-05-14 21:29 UTC, TFK70 commented on practice/my-diary/ui/input/src/Input.tsx
> +    border: '1px solid #e4eaff',
тут есть захардкоженные цвета
чтобы взять цвет из темы можно:
а) Принять проп theme и брать оттуда
б) Дать инпуту проп color из styled-system и передавать borderColor и другие цвета в defaultProps (наиболее предпочтительный и красивый вариант)

2021-05-14 21:29 UTC, TFK70 commented on practice/my-diary/ui/drawer/src/Drawer.tsx
> +    backgroundColor: '#fff',
Даже несмотря на то, что это всего лишь белый, он должен браться из темы

2021-05-14 21:29 UTC, TFK70 commented on practice/my-diary/ui/drawer/src/Drawer.tsx
> +    backgroundColor: 'transperent',
Тут опечатка
Это значит что свойство не применилось, а если оно не применилось и ничего не произошло - значит оно тут и не надо

2021-05-14 21:29 UTC, TFK70 commented on practice/my-diary/ui/drawer/src/Drawer.tsx
> +      to: { backgroundColor: 'rgba(0,0,0,0.2)', visibility: 'visible' },
Кстати этот цвет тоже из темы нужно взять

2021-05-14 21:29 UTC, TFK70 commented on practice/my-diary/ui/button/src/Button.tsx
>    color: '#6c757d',
Ну тут вообще по всему приложению в поиске таких мест надо пройтись, видимо

2021-05-14 21:29 UTC, TFK70 commented on practice/my-diary/components/post-controls/src/PostControls.tsx
> +              border='1px solid #e4eaff'
Тоже

2021-05-14 21:29 UTC, TFK70 commented on practice/my-diary/app/src/App.tsx
> +      id: uniqueKey(),
На самом деле генерацию id лучше скрыть внутри листа, чем постоянно заморачиваться по этому поводу создавая новую тудушку

2021-05-14 21:29 UTC, TFK70 commented on practice/my-diary/app/src/App.tsx
> +      id: uniqueKey(),
И это надо учесть в экшене который создает тудушку

2021-05-14 21:29 UTC, TFK70 commented on practice/my-diary/app/src/App.tsx
> +                margin='auto'
margin? Он тут нужен?

2021-05-15 08:09 UTC, TFK70 requested changes

2021-05-15 08:09 UTC, TFK70 commented on practice/my-diary/ui/theme/src/shadows.ts
> +  grey: '0 0 10px rgba(0,0,0,0.5)',
grAy*

2021-05-15 08:09 UTC, TFK70 commented on practice/my-diary/app/src/App.tsx
> +      id: 1,
Я другое имел ввиду
Сейчас чтобы добавить тудушку тебе самой предварительно необходимо сгенерировать айдишник, это некорректно, его нужно генерировать внутри листа, тк id с точки зрения данных имеет ценность только технического характера, в отличие от всех остальных свойств

2021-05-15 08:09 UTC, TFK70 commented on practice/my-diary/app/src/App.tsx
>        onHover: false,
С этим то же самое

Отслеживать onHover на конкретной тудушке можно инициализировав в айтеме локальную переменную состояния и повесив на него события, тк переменная локальная у каждой тудушки будет свой независимый hover

2021-05-15 17:13 UTC, ikorol3107 commented on practice/my-diary/app/src/App.tsx
> +      id: 1,
@TFK70 но ведь мы еще используем айдишник в экшэнах , например в toggleStatus:
```javascript
export const toggleStatus = (notes, id, value) => {
  const index = notes.findIndex(customElements => customElements.id === id)
  const lastNote = notes[index]
  let newNote
  if (value === 'onHover') {
    newNote = { ...lastNote, onHover: !lastNote.onHover }
...
...
```

2021-05-15 17:46 UTC, TFK70 commented on practice/my-diary/app/src/App.tsx
> +      id: 1,
@ikorol3107 я про это тоже упоминал, но коммент где-то решил потеряться..
В теории можно оставить генерацию айдишника в этом экшене, тогда тебе придется прогнать начальное состояние с твоими тудушками через него, чтобы айдишник для каждого сгенерился

2021-05-15 17:49 UTC, TFK70 commented on practice/my-diary/app/src/App.tsx
> +      id: 1,
@ikorol3107  а в том экшене который ты написала вообще же проблем быть не должно
Внутри айтема у тебя будет айдишник для тудушки, но этот айдишник будет не прокидываться через пропсы (List->Item->action), а генерироваться в List и потом передаваться в Item

2021-05-16 14:32 UTC, ikorol3107 commented on practice/my-diary/app/src/App.tsx
> +      id: 1,
@TFK70 я создаю в List новый массив данных newNotes (чтобы не изменять напрямую массив notes) , в котором у каждой note добавляю id и передаю этот массив в Item. Но тогда все actions ломаются, они же привязаны к notes.

2021-05-16 14:42 UTC, TFK70 commented on practice/my-diary/app/src/App.tsx
> +      id: 1,
@ikorol3107 полагаю ломаются точечные экшены по типу удаления, для которых нужны айдишники, но все эти экшены вызываются внутри Item, а там у тебя id есть, его можно передавать в экшен как доп аргумент

Но основная проблема состояла в том, что айишники для тудушек выставлялись руками. Этого можно избежать и другим путём: задавая initial state для note вызывая экшен содания тудушки вручную. Этот вызов можно засунуть как раз в useEffect, в компоненте где у тебя этот экшен присутствует, тк задать начальное состояние необходимо только единственный раз при загрузке приложения

2021-05-16 17:19 UTC, TFK70 requested changes

2021-05-16 17:19 UTC, TFK70 commented on practice/my-diary/ui/list/src/List.tsx
> +          key={Math.random() * Date.now()}
Почему так? У них же есть поле id
По крайней мере должно быть

2021-05-16 17:19 UTC, TFK70 commented on practice/my-diary/components/post-list/src/actions/addId.ts
> +  notes.forEach(item => {
А точно ли есть необходимость в этом экшене? У тебя уже есть addItem который создает тудушку вместе с айди, можно просто вызывать его с нужными данными и всё, и тогда даже не придется лишний раз полный обход массива делать

2021-05-16 17:19 UTC, TFK70 commented on practice/my-diary/components/post-list/src/PostList.tsx
> +    return setNotes(addId(notes))
Не могу понять почему здесь return

Если что в return обычно суётся коллбек. Этот коллбек выполняется при анмаунте компонента
А конкретно в этой записи смысла нет, тк setNotes() вызовется при маунте в любом случае, что с return, что без него (опять же потому что отложенный вызов функции реализуется через коллбек)

2021-05-16 18:24 UTC, ikorol3107 commented on practice/my-diary/ui/list/src/List.tsx
> +          key={Math.random() * Date.now()}
@TFK70 потому-что варнинг дает, если item.id осатвить: Each child in a list should have a unique "key" prop.

2021-05-16 18:27 UTC, TFK70 commented on practice/my-diary/ui/list/src/List.tsx
> +          key={Math.random() * Date.now()}
@ikorol3107 этот ворнинг возникает только в 2 ситуациях:
1. У компонентов нету ключей
2. У компонентов не уникальные ключи

Тк ключи есть - обрати внимание на второе. Расставь логи, продебажь, проверь что не так с ключами

2021-05-16 19:57 UTC, ikorol3107 commented on practice/my-diary/ui/list/src/List.tsx
> +          key={Math.random() * Date.now()}
@TFK70 ключи уникальные, только почему-то два рендера при обновлении страницы: первый рендер  notes без айдишников, и следом второй рендер уже с айдишниками. И ворнинг между ними выскакивает, что ключи не уникальны.

2021-05-17 11:46 UTC, ikorol3107 commented on practice/my-diary/ui/list/src/List.tsx
> +          key={Math.random() * Date.now()}
@TFK70 а-а-а, а как же я передам изначальный массив записей сюда
```javascript
 useEffect(() => {
    setNotes(addItem(notes , 'Flight to Moscow'))
  }, [])
```
, если экшн adItem принимает вторым аргументом строку, а не массив.

2021-05-17 11:52 UTC, TFK70 commented on practice/my-diary/ui/list/src/List.tsx
> +          key={Math.random() * Date.now()}
@ikorol3107 если необходим массив - можно создать массив из тудушек и на каждой итерации по нему вызывать addItem

Ну или просто 3 раза его вызвать

Но вообще наиболее правильным решением будет сделать отдельный экшен fetchInitialData, который будет сетать исходные данные. Внутри него можно и addItem задействовать, чтобы логику не дублировать

2021-05-17 15:30 UTC, TFK70 requested changes

2021-05-17 15:30 UTC, TFK70 commented on practice/my-diary/fragments/form-add-post/src/FormAddPost.tsx
> +  const initialNotes = ['Flight to Moscow', 'Friends meeting', 'Buy a new frying pan in Ikea']
fetch === извлечь

Т.е. твои данные должны браться внутри fetchInitialData, желательно завести с ними отдельный файл и брать оттуда

2021-05-17 15:30 UTC, TFK70 commented on practice/my-diary/fragments/form-add-post/src/actions/fetchInitialData.ts
> +  textArray.forEach(text => {
И раз уж это происходит в том же фрагменте где есть addItem - то наиболее целесообразно будет этот addItem здесь и использовать, чтобы не дублировать логику

2021-05-17 15:38 UTC, ikorol3107 commented on practice/my-diary/fragments/form-add-post/src/actions/fetchInitialData.ts
> +  textArray.forEach(text => {
@TFK70 не очень поняла тебя. Ты предлагаешь назвать этот экшн "addItem", а файл с начальными значениями записей - fetchInitialData ?

2021-05-17 15:38 UTC, TFK70 commented on practice/my-diary/fragments/form-add-post/src/actions/fetchInitialData.ts
> +  textArray.forEach(text => {
@ikorol3107 нет, у тебя же уже есть экшен для добавления айтема, я предлагаю им здесь и вопспользоваться

2021-05-17 15:41 UTC, ikorol3107 commented on practice/my-diary/fragments/form-add-post/src/actions/fetchInitialData.ts
> +  textArray.forEach(text => {
@TFK70 нет такого экшена, я его убрала.

2021-05-17 15:42 UTC, TFK70 commented on practice/my-diary/fragments/form-add-post/src/actions/fetchInitialData.ts
> +  textArray.forEach(text => {
@ikorol3107 а
а зачем?)
fetchInitialData вызывается только один раз - чтобы получить начальное состояние, для добавления айтемов по-прежнему используется addItem

2021-05-17 15:44 UTC, TFK70 commented on practice/my-diary/fragments/form-add-post/src/actions/fetchInitialData.ts
> +  textArray.forEach(text => {
@ikorol3107 то есть у тебя есть addItem, есть файлик с входными данными для твои тудушек. Нужно создать экшен fetchInitialData который будет брать данные из файлика и приводить их к нужному виду с помощью addItem

2021-05-17 15:46 UTC, ikorol3107 commented on practice/my-diary/fragments/form-add-post/src/actions/fetchInitialData.ts
> +  textArray.forEach(text => {
@TFK70 то есть сделать в этом фрагменте два экшена все-таки?

2021-05-17 15:47 UTC, TFK70 commented on practice/my-diary/fragments/form-add-post/src/actions/fetchInitialData.ts
> +  textArray.forEach(text => {
@ikorol3107 да

2021-05-17 16:41 UTC, ikorol3107 commented on practice/my-diary/fragments/form-add-post/src/actions/fetchInitialData.ts
> +  textArray.forEach(text => {
@TFK70 если вызываю в fetchInitialData экшен addItem, то литер матерится: `Arrow function should not return assignment  no-return-assign`
```javascript
import { initialNotes } from '../initialNotes'
import { addItem }      from './addItem'

export const fetchInitialData = notes => {
  let newNotes = []
  initialNotes.forEach(text => (newNotes = addItem(newNotes, text) ) )
  return notes.concat(newNotes)
}
```

2021-05-17 16:44 UTC, TFK70 commented on practice/my-diary/fragments/form-add-post/src/actions/fetchInitialData.ts
> +  textArray.forEach(text => {
@ikorol3107 попробуй [...notes, newNotes]
И файл с начальными значениями лучше помести в одну директорию с экшенами и назови mocks

2021-05-17 17:41 UTC, ikorol3107 commented on practice/my-diary/fragments/form-add-post/src/actions/fetchInitialData.ts
> +  textArray.forEach(text => {
@TFK70  да тут вобще можно notes не передавать, они тут не используются. переделала так: 
```javascript
import { addItem } from './addItem'
import { mocks }   from './mocks'

export const fetchInitialData = () => {
  let newNotes = []
  mocks.forEach(text => (newNotes = addItem(newNotes, text)))
  return newNotes
}
```
но проблема ` error  Arrow function should not return assignment  no-return-assign` осталась

2021-05-17 18:28 UTC, TFK70 submitted a review, later dismissed

2021-05-17 22:14 UTC, TorinAsakura requested changes

2021-05-17 22:14 UTC, TorinAsakura commented on practice/my-diary/app/src/App.tsx
> +              <Box
в app должен проходить лишь маунт, ничего больше

2021-05-17 22:18 UTC, TorinAsakura requested changes
В общем-то - идём к финалу, совсем мелочи осталось

2021-05-17 22:18 UTC, TorinAsakura commented on practice/my-diary/fragments/form-add-post/src/actions/addItem.ts
> +import { nanoid } from 'nanoid'
это тут зачем?

2021-05-17 22:18 UTC, TorinAsakura commented on practice/my-diary/ui/icons/icons/circleDot.svg
> +</g>
это что за жесть?

2021-05-17 22:18 UTC, TorinAsakura commented on practice/my-diary/ui/icons/icons/gamburgerMenu.svg
> +<?xml version="1.0" encoding="iso-8859-1"?>
gamburger пишется как hamburger, а мы называем его коротко - burger

2021-05-18 08:18 UTC, ikorol3107 commented on practice/my-diary/fragments/form-add-post/src/actions/addItem.ts
> +import { nanoid } from 'nanoid'
чтобы создать уникальный id и key  у айтемов при самом первом рендеринге, т.к. у меня key={item.id} . Пробовала делать с помощью  `Math.round(Math.random()*5)+Date.now()` , все равно с высоким процентом вероятности генерит повторяющиеся значения.

2021-05-18 14:24 UTC, TFK70 approved these changes, later dismissed

2021-05-18 19:36 UTC, TorinAsakura requested changes

2021-05-18 19:36 UTC, TorinAsakura commented on practice/my-diary/fragments/form-add-post/src/FormAddPost.tsx
> +      <Button
Кнопка не должна быть похожа на мутанта. Вы что-то делаете не так. Сильно не так.

2021-05-18 23:15 UTC, TorinAsakura requested changes

2021-05-18 23:15 UTC, TorinAsakura commented on practice/my-diary/fragments/diary/src/Diary.tsx
> +      backgroundColor='purple'
аналогично

2021-05-18 23:15 UTC, TorinAsakura commented on practice/my-diary/fragments/form-add-post/src/actions/mocks.ts
> +export const mocks = ['Flight to Moscow', 'Friends meeting', 'Buy a new frying pan in Ikea']
разбей строку

2021-05-18 23:15 UTC, TorinAsakura commented on practice/my-diary/ui/button/src/AddTaskButton.tsx
> +export const AddTaskButton = ({ onClick, children }) => {
кнопка - это кнопка, она никоим образом не должна быть привязана к контексту. Ну, то есть, у тебя появится remove task, тоже создашь отдельную кнопку?

2021-05-18 23:15 UTC, TorinAsakura commented on practice/my-diary/ui/button/src/AddTaskButton.tsx
> +      onClick={onClick}
очень много надстроек, ты точно что-то делаешь не так

2021-05-18 23:15 UTC, TorinAsakura commented on practice/my-diary/ui/icons/icons/dot.svg
> +</g>
?

2021-05-19 08:43 UTC, TFK70 requested changes

2021-05-19 08:43 UTC, TFK70 commented on practice/my-diary/fragments/form-add-post/src/actions/mocks.ts
> +export const mocks = ['Flight to Moscow', 'Friends meeting', 'Buy a new frying pan in Ikea']
@ikorol3107 разбей
каждому значению свою строку

2021-05-19 08:43 UTC, TFK70 commented on practice/my-diary/fragments/form-add-post/src/FormAddPost.tsx
> +            setInputStatus('visible')
Если у inputStatus бинарное значение - используй бул
И переименуй в isVisible

2021-05-19 08:43 UTC, TFK70 commented on practice/my-diary/fragments/form-add-post/src/FormAddPost.tsx
> +            if (inputStatus === 'visible' && newNote !== '') {
Саму функцию можно выстроить по-другому
```javascript
if (isVisible && newNote) {
   setNotes(addItem(...))
   setNewNote('')
   setVisible(false)
} else {
   setVisible(true)
}
```

2021-05-19 09:38 UTC, ikorol3107 commented on practice/my-diary/fragments/form-add-post/src/FormAddPost.tsx
> +            if (inputStatus === 'visible' && newNote !== '') {
@TFK70 нет, если второе условие убрать ( else if (isVisible) ) , то инпут вообще не откроется

2021-05-19 09:42 UTC, TFK70 commented on practice/my-diary/fragments/form-add-post/src/FormAddPost.tsx
> +            if (inputStatus === 'visible' && newNote !== '') {
@ikorol3107 только что проверил - все работает

2021-05-19 09:42 UTC, ikorol3107 commented on practice/my-diary/fragments/form-add-post/src/FormAddPost.tsx
> +            setInputStatus('visible')
@TFK70  "разбей каждому значению свою строку" - типа просто строчки перенести , не пойму?
```javascript
export const mocks = [
    'Flight to Moscow',
    'Friends meeting',
    'Buy a new frying pan in Ikea'
  ]
```

2021-05-19 09:47 UTC, TFK70 commented on practice/my-diary/fragments/form-add-post/src/FormAddPost.tsx
> +            setInputStatus('visible')
@ikorol3107 да, так же читабельнее

2021-05-19 09:50 UTC, ikorol3107 commented on practice/my-diary/fragments/form-add-post/src/FormAddPost.tsx
> +            setInputStatus('visible')
@TFK70 а линтер так не считает)

2021-05-19 09:51 UTC, TFK70 commented on practice/my-diary/fragments/form-add-post/src/FormAddPost.tsx
> +            setInputStatus('visible')
@ikorol3107 нуу тогда оставь как есть

2021-05-19 10:12 UTC, ikorol3107 commented on practice/my-diary/fragments/form-add-post/src/FormAddPost.tsx
> +            if (inputStatus === 'visible' && newNote !== '') {
@TFK70 а , да, ты прав. Открывается, но если ничего не ввести в поле инпут , то при повторном нажатии кнопки инпут не исчезает.

2021-05-19 10:14 UTC, TFK70 commented on practice/my-diary/fragments/form-add-post/src/FormAddPost.tsx
> +            if (inputStatus === 'visible' && newNote !== '') {
@ikorol3107 тогда экстенди эту логику, это же просто набросок более чистого формата кода
Добавь доп действия если необходимо, доп проверки (но сильно не вкладывай проверки друг в друга, чтобы читабельность сохранялась, а лучше вообще такого нестинга избегать)

2021-05-19 11:25 UTC, TorinAsakura commented on practice/my-diary/fragments/form-add-post/src/FormAddPost.tsx
> +            setInputStatus('visible')
@ikorol3107 так ты про глаза и голову-то не забывай, завтра линтер словит апдейт ломающий поддержку латиницы и скажет писать на Китайском.

Делай как я говорю а линтеру поставь на этом блоке дизейбл

2021-05-19 11:28 UTC, TorinAsakura requested changes

2021-05-19 11:28 UTC, TorinAsakura commented on practice/my-diary/fragments/form-add-post/src/FormAddPost.tsx
> +          border='none'
на кнопку мутагена вылили снова?

2021-05-19 11:29 UTC, TFK70 commented on practice/my-diary/fragments/form-add-post/src/FormAddPost.tsx
> +          border='none'
@TorinAsakura ненужных пропертей тут нет, там кнопка сама по себе навороченная

2021-05-19 11:30 UTC, TorinAsakura commented on practice/my-diary/fragments/form-add-post/src/FormAddPost.tsx
> +          border='none'
так быть может это в таком случае отдельная кнопка или типа того? зачем это за пределы компонента выносить?

2021-05-19 11:30 UTC, TorinAsakura commented on practice/my-diary/fragments/form-add-post/src/FormAddPost.tsx
> +          border='none'
то есть fit-content у вас это кастомный случай?

2021-05-19 11:31 UTC, TorinAsakura commented on practice/my-diary/fragments/form-add-post/src/FormAddPost.tsx
> +          border='none'
зачем тут используется margin-top отрицательный когда это решается layout 30px?

2021-05-19 11:31 UTC, TorinAsakura commented on practice/my-diary/fragments/form-add-post/src/FormAddPost.tsx
> +          border='none'
мне продолжить?

2021-05-19 11:49 UTC, TFK70 commented on practice/my-diary/fragments/form-add-post/src/FormAddPost.tsx
> +          border='none'
> зачем тут используется margin-top отрицательный когда это решается layout 30px?

тут важно чтобы сдвиг элемента на поток не влиял, через маржин это проще всего решается

2021-05-19 11:50 UTC, TorinAsakura commented on practice/my-diary/fragments/form-add-post/src/FormAddPost.tsx
> +          border='none'
как раз-таки вот для этого я и придумал тему с блочными модификаторами, они-то как раз и не повлияют ни на что, а вот твой марджин, при определённых условиях может сломаться

2021-05-19 19:50 UTC, TFK70 requested changes

2021-05-19 19:50 UTC, TFK70 commented on practice/my-diary/fragments/diary/src/Diary.tsx
> +            <FormAddPost />
Немного поехало
![image](https://user-images.githubusercontent.com/62806448/118875219-3760d500-b905-11eb-9d30-aa6bbe9adf06.png)

2021-05-19 19:50 UTC, TFK70 commented on practice/my-diary/ui/button/src/GiantButton.tsx
> +    height: '80px',
Это лучше в defaultProps вынести

2021-05-19 20:19 UTC, TFK70 requested changes

2021-05-19 20:19 UTC, TFK70 commented on practice/my-diary/fragments/form-add-post/src/FormAddPost.tsx
> +          <Layout flexBasis={80} />
У меня он все еще поехавший
Отцентрируй через justifyContent

2021-05-19 20:24 UTC, ikorol3107 commented on practice/my-diary/fragments/form-add-post/src/FormAddPost.tsx
> +          <Layout flexBasis={80} />
@TFK70 Ок, а подскажи, пожалуйста, почему я в mocks разделяю строчки - сделала `/* eslint-disable */` и все равно в одну строчку при прекоммите возвращается выражение.

2021-05-19 20:26 UTC, TFK70 commented on practice/my-diary/fragments/form-add-post/src/FormAddPost.tsx
> +          <Layout flexBasis={80} />
@ikorol3107 сделай к нему `// eslint-disable-next-line`

2021-05-19 20:27 UTC, ikorol3107 commented on practice/my-diary/fragments/form-add-post/src/FormAddPost.tsx
> +          <Layout flexBasis={80} />
@TFK70  что касается инпута - ты хочешь его по центру? Я делала его так, чтоб текст плэйсхолдера был на уровне с текстом уже существующих сообщений, поэтому не по центру.  Но если надо по центру, то ок, переделаю.

2021-05-19 20:29 UTC, TFK70 commented on practice/my-diary/fragments/form-add-post/src/FormAddPost.tsx
> +          <Layout flexBasis={80} />
@ikorol3107 мне казалось он и раньше был по центру если честно
Ну так он более привычно смотрится, так что да, лучше по центру

2021-05-19 20:52 UTC, TFK70 requested changes

2021-05-19 20:52 UTC, TFK70 commented on practice/my-diary/fragments/form-add-post/src/actions/mocks.ts
>  export const mocks = ['Flight to Moscow', 'Friends meeting', 'Buy a new frying pan in Ikea']
Это делает формат в прекоммит хуке
Переведи строки и убери хаски только для этого коммита

2021-05-19 21:13 UTC, TFK70 submitted a review, later dismissed

2021-05-20 13:53 UTC, TorinAsakura requested changes

2021-05-20 13:53 UTC, TorinAsakura commented on practice/my-diary/fragments/diary/src/Diary.tsx
> +      </Row>
Я вот чот не вкурю ваш флоу
строка
  - колонка
  - - колонка
  
Зачем?

2021-05-20 13:53 UTC, TorinAsakura commented on practice/my-diary/fragments/form-add-post/src/FormAddPost.tsx
> +      <Column backgroundColor='white'>
зачем пустая колонка в которой…колонка?

2021-05-20 13:53 UTC, TorinAsakura commented on practice/my-diary/fragments/diary/src/Diary.tsx
> +          </Column>
строка в которой колонка в которой колонка - зачем?

2021-05-20 13:53 UTC, TorinAsakura commented on practice/my-diary/fragments/form-add-post/src/FormAddPost.tsx
> +import { GiantButton }                from '@ui/button'
Giant - модификатор, а не сущность

2021-05-20 13:53 UTC, TorinAsakura commented on practice/my-diary/fragments/form-add-post/src/actions/mocks.ts
>  export const mocks = ['Flight to Moscow', 'Friends meeting', 'Buy a new frying pan in Ikea']
так а чо не разбили-то?

2021-05-20 13:53 UTC, TorinAsakura commented on practice/my-diary/ui/background/src/Background.tsx
> +    width: '100vw',
зачем вы задаёте 100 величины от viewport да ещё и с fixed?

2021-05-20 13:53 UTC, TorinAsakura commented on practice/my-diary/ui/button/src/GiantButton.tsx
> +    width: 'fit-content',
не понимаю зачем это потребовалось

2021-05-20 13:57 UTC, TFK70 commented on practice/my-diary/fragments/form-add-post/src/actions/mocks.ts
>  export const mocks = ['Flight to Moscow', 'Friends meeting', 'Buy a new frying pan in Ikea']
@TorinAsakura помимо линтера это еще и форматтер в прекоммите правит

2021-05-20 17:24 UTC, TFK70 requested changes

2021-05-20 17:24 UTC, TFK70 commented on practice/my-diary/fragments/form-add-post/src/FormAddPost.tsx
> +        <Condition visible={isVisible}>
Забыл сказать: проп должен называться match
Виноват

2021-05-20 17:24 UTC, TFK70 commented on practice/my-diary/ui/condition/src/Condition.tsx
> +  return <Box display={visible ? 'flex' : 'none'}>{children}</Box>
Вообще будет правильнее сделать так:
1. Принимать на вход children
2. Если match - возвращаешь children
3. Если !match - не возвращаешь ничего (но не надо писать null, в таких случаях просто возвращай пустой объект)

2021-05-20 17:47 UTC, ikorol3107 commented on practice/my-diary/fragments/form-add-post/src/FormAddPost.tsx
> +import { GiantButton }                from '@ui/button'
@TFK70 Как тут поправить?

2021-05-22 08:33 UTC, TFK70 requested changes

2021-05-22 08:33 UTC, TFK70 commented on practice/my-diary/ui/filter/src/Filter.tsx
> +export const Filter = ({ filter, setFilter, messages }) => {
Тебе нужно сделать так: компонент должен принимать на вход массив из строк (массив из intl.formatMessage), а из этих строк собирать кнопки фильтров, давая филтру соответствующее состояние

2021-05-22 08:33 UTC, TFK70 commented on practice/my-diary/ui/layout/src/Box.tsx
> +  border: '1px solid #e4eaff',
Захардкоженный цвет

2021-05-22 08:33 UTC, TFK70 commented on practice/my-diary/ui/list/src/Item.tsx
> +          cursor='pointer'
Не надо задавать боксу поинтер, если элемнет кликабельный и тп - сделай его баттоном

2021-05-22 08:33 UTC, TFK70 commented on practice/my-diary/ui/list/src/Item.tsx
> +          cursor='pointer'
И тогда в ui в самом компоненте опцию cursor нужно убрать

2021-05-22 08:33 UTC, TFK70 commented on practice/my-diary/ui/layout/src/Box.tsx
> +  fontSize: 15,
Захардкоженное значение

2021-05-22 11:30 UTC, TorinAsakura requested changes

2021-05-22 11:30 UTC, TorinAsakura commented on practice/my-diary/fragments/post-controls/src/PostControls.tsx
> +            <Space count={2} />
реализация паддингов через пробелы? сильно!

2021-05-22 11:30 UTC, TorinAsakura commented on practice/my-diary/ui/background/src/Background.tsx
> +    height: '100vh',
зачем тебе 100vh? почему не cover?

2021-05-22 11:30 UTC, TorinAsakura commented on practice/my-diary/ui/button/src/Button.tsx
> +  backgroundColor: 'deepPurple',
ROCK!

2021-05-22 11:30 UTC, TorinAsakura commented on practice/my-diary/ui/button/src/Button.tsx
> +  fontSize: 32,
почему у тебя фонтсайз в кнопке?

2021-05-22 11:30 UTC, TorinAsakura commented on practice/my-diary/ui/button/src/Button.tsx
>  export const Button = styled.button(
ты же в курсе, что у тебя кнопка имеет свойство display block по умолчанию?

2021-05-22 11:30 UTC, TorinAsakura commented on practice/my-diary/ui/filter/src/Filter.tsx
> +      </Box>
Вы там что курили?

2021-05-22 11:30 UTC, TorinAsakura commented on practice/my-diary/ui/input/src/Input.tsx
>      display: 'block',
почему у тебя block если мы работаем в флексовой среде?

2021-05-22 11:30 UTC, TorinAsakura commented on practice/my-diary/ui/layout/src/Box.tsx
>    fontFamily: ['Roboto', 'Ubuntu', 'sans-serif'],
зачем в боксе у тебя проброшен fontFamily?

2021-05-22 11:30 UTC, TorinAsakura commented on practice/my-diary/ui/layout/src/Box.tsx
> +    visibility: true,
это тут зачем?

2021-05-22 11:30 UTC, TorinAsakura commented on practice/my-diary/ui/input/src/Input.tsx
> +  overflowWrap: 'break-word',
это зачем?

2021-05-25 17:11 UTC, TFK70 requested changes

2021-05-25 17:11 UTC, TFK70 commented on practice/my-diary/ui/input/src/addons/ClearButton.tsx
> +// TODO rewrite with UI Button
Ну не настолько же копипастить...

2021-05-25 17:11 UTC, TFK70 commented on practice/my-diary/ui/input/src/addons/ClearButton.tsx
> +const StyledButton = styled.button(createBaseStyles(), appearanceStyles, shapeStyles)
И в этом месте не должно быть create функций. Они создают styleFn, для styleFn ты создаешь отдельный файлик Input.styles.ts (который у тебя уже есть), оттуда их и берешь

Т.е. сюда ты прокидываешь вместо createBaseStyles() просто baseStyles:

```javascript
const baseStyles = createBaseStyles()
```

2021-05-25 17:11 UTC, TFK70 commented on practice/my-diary/ui/input/src/addons/ClearButton.styles.ts
> +  borderRadius: '0 15px 15px 0',
А тема тогда зачем?

2021-05-25 17:11 UTC, TFK70 commented on practice/my-diary/ui/button/src/Button.tsx
> +      justifyContent: 'center',
Его тоже надо переписать в похожем с input стиле

Настоятельно рекомендую руководствоваться собственной смекалкой и ничего не копипастить, тут никакого рокет-саенса нет и все вполне логично

2021-05-25 19:29 UTC, ikorol3107 commented on practice/my-diary/ui/input/src/addons/ClearButton.tsx
> +// TODO rewrite with UI Button
Делала инпут отдельным коммитом,  поэтому так написала. Сейчас сделала button  по такому же принципу и убрала эту тудушку)

2021-05-25 19:32 UTC, TFK70 commented on practice/my-diary/ui/input/src/addons/ClearButton.tsx
> +// TODO rewrite with UI Button
@ikorol3107 тогда gut

2021-05-26 10:06 UTC, TFK70 requested changes

2021-05-26 10:06 UTC, TFK70 commented on practice/my-diary/ui/filter/src/Filter.tsx
>    const checkButtonPlace = (option, index) => {
1. Здесь option не используется
2. options берется из глобального скоупа. В utils функциях такого лучше избегать, так что передавай все необходимые для работы функции данные в ее аргументах
Это необходимо чтобы результат работы функции был более предсказуемый, чтобы не пришлось рыскать по всему коду и искать откуда-же он этот options берёт

2021-05-26 10:06 UTC, TFK70 commented on practice/my-diary/ui/input/src/Input.tsx
> +          <Text color='white'>{addonName}</Text>
Это необходимо?
Если я использую аддон search - то мне вряд ли будет нужно менять текс у баттона, который там появляется. Это лучше написать с помощью интла

Ну или аналогия с тем же clear аддоном. Что еще я могу написать внутри ClearButton кроме как "Clear"?

2021-05-26 10:06 UTC, TFK70 commented on practice/my-diary/ui/input/src/parts/StyledInput.styles.ts
>    fontSize: 15,
Это тоже из темы

2021-05-26 14:54 UTC, ikorol3107 commented on practice/my-diary/ui/filter/src/Filter.tsx
>    const checkButtonPlace = (option, index) => {
@TFK70 
1. да, поняла.
2. options это массив из messages. Не понимаю, как его передать в аргументах иначе %-/

2021-05-26 15:00 UTC, ikorol3107 commented on practice/my-diary/ui/input/src/Input.tsx
> +          <Text color='white'>{addonName}</Text>
@TFK70 логично, согласна. Сделать файл messages в инпуте получается?

2021-05-26 16:12 UTC, TFK70 commented on practice/my-diary/ui/input/src/Input.tsx
> +          <Text color='white'>{addonName}</Text>
@ikorol3107 да

2021-05-26 16:14 UTC, TFK70 commented on practice/my-diary/ui/filter/src/Filter.tsx
>    const checkButtonPlace = (option, index) => {
@ikorol3107 создай checkButtonPlace за пределами Filter и передай туда options

2021-05-26 17:10 UTC, ikorol3107 commented on practice/my-diary/ui/input/src/Input.tsx
> +          <Text color='white'>{addonName}</Text>
@TFK70 при попытке  в инпуте использовать интл выдает ошибку:
`utils.js:89 Uncaught Error: [React Intl] Could not find required `intl` object. <IntlProvider> needs to exist in the component ancestry.` Не понимаю почему, у меня же весь App обернут в <IntlProvider>...

2021-05-26 21:25 UTC, TFK70 requested changes

2021-05-26 21:25 UTC, TFK70 commented on practice/my-diary/ui/filter/src/actions/checkButtonPlace.ts
> +export const checkButtonPlace = (index, lastOption) => {
Да, так даже будет лучше чем все в одном файле держать, но это не экшен. Это хелпер, тут нет какой-то конкретной логики по типу "сходить в базу". Такие функции нужно держать в utils

2021-05-26 21:25 UTC, TFK70 commented on practice/my-diary/ui/input/src/Input.tsx
> +      <StyledInput placeholder={intl.formatMessage(messages.search)} {...props} />
А вот насчет насчет плейсхолдера не уверен
Аддон search-то у тебя опциональный, получается без него, если инпут нам нужен, например, для ввода пароля, то там тоже будет плейсхолдер "Поиск"?

2021-05-26 21:25 UTC, TFK70 commented on practice/my-diary/ui/input/src/parts/StyledInput.styles.ts
> +    fontFamily: 'Gordita, sans-serif',
Нууу так и и это тоже из темы

2021-05-26 21:25 UTC, TFK70 commented on practice/my-diary/ui/text/src/Text.tsx
>    fontFamily: ['Segoe UI', 'Roboto', 'Ubuntu', 'sans-serif'],
Это страшно и, вероятнее всего, не нужно
А если и нужно - вынеси в тему

2021-05-26 21:25 UTC, TFK70 commented on practice/my-diary/ui/text/src/Text.tsx
>    textDecorationColor: '#e4eaff',
Тоже цвет захардкоженный

2021-05-27 08:23 UTC, ikorol3107 commented on practice/my-diary/ui/text/src/Text.tsx
>    textDecorationColor: '#e4eaff',
@TFK70 да, тут fontFamily и  textDecorationColor берутся не из темы, если подставлять значения темы, хотя fontSize, например, идет из нее. Не могу разобраться.

2021-05-27 08:29 UTC, TFK70 commented on practice/my-diary/ui/text/src/Text.tsx
>    textDecorationColor: '#e4eaff',
@ikorol3107 ну за это у тебя отвечал styled system, значит в color нет textDecorationColor и его надо разрешить самому

Ааа зачем тексту textDecorationColor?

2021-05-27 08:34 UTC, ikorol3107 commented on practice/my-diary/ui/text/src/Text.tsx
>    textDecorationColor: '#e4eaff',
@TFK70 чтоб у линии зачеркивания был нужный мне цвет.

2021-05-27 08:45 UTC, TFK70 commented on practice/my-diary/ui/text/src/Text.tsx
>    textDecorationColor: '#e4eaff',
@ikorol3107 ок
Взять из темы получилось?

2021-05-27 08:48 UTC, ikorol3107 commented on practice/my-diary/ui/text/src/Text.tsx
>    textDecorationColor: '#e4eaff',
@TFK70 нет

2021-05-27 09:07 UTC, TFK70 commented on practice/my-diary/ui/text/src/Text.tsx
>    textDecorationColor: '#e4eaff',
@ikorol3107 тебе не обязательно использовать styled-system для темизации, можешь сама написать это:
```javascript
({ textDecorationColor }) => ({
   textDecorationColor: theme.colors[textDecorationColor] || textDecorationColor
})
```

2021-05-27 10:40 UTC, TFK70 requested changes

2021-05-27 10:40 UTC, TFK70 commented on practice/my-diary/ui/input/src/parts/StyledInput.styles.ts
> +    fontFamily: theme.fonts.standart,
standarD

2021-05-27 10:40 UTC, TFK70 commented on practice/my-diary/ui/input/src/parts/StyledInput.styles.ts
> +    fontFamily: theme.fonts.standart,
это пахнет немецким

2021-05-27 10:40 UTC, TFK70 commented on practice/my-diary/ui/text/src/Text.tsx
> +const decorationColor = switchProp('decorationColor', ({ theme }) => ({
1. Это можно не выносить в отдельную функцию
2. Код который я привел в пример должен быть вполне рабочим

На данный момент твоя задача самой реализовать функционал темизации предоставлямый styled-system, у тебя нет задачи стандартизации

2021-05-27 11:02 UTC, ikorol3107 commented on practice/my-diary/ui/text/src/Text.tsx
> +const decorationColor = switchProp('decorationColor', ({ theme }) => ({
@TFK70 я туплю что-то с темизацией жестко. Имеешь ввиду, что в самом Text так писать?:
```javascript
export const Text = styled.span(
  ({ textDecorationColor }) => ({
    textDecorationColor: theme.colors[textDecorationColor] || textDecorationColor
  }),
  system({
    wordBreak: true,
    whiteSpace: true,
    ...
```

2021-05-27 11:09 UTC, TFK70 commented on practice/my-diary/ui/text/src/Text.tsx
> +const decorationColor = switchProp('decorationColor', ({ theme }) => ({
@ikorol3107 ну да, так не работает?

2021-05-27 11:15 UTC, ikorol3107 commented on practice/my-diary/ui/text/src/Text.tsx
> +const decorationColor = switchProp('decorationColor', ({ theme }) => ({
@TFK70 так не работает. Пишет, что `Cannot find name 'theme'`

2021-05-27 11:16 UTC, TFK70 commented on practice/my-diary/ui/text/src/Text.tsx
> +const decorationColor = switchProp('decorationColor', ({ theme }) => ({
@ikorol3107 во-первых саму тему тебе тоже нужно откуда-то брать, во-вторых если ты пишешь свой коллбек до system, а из самого system не убираешь textDecorationColor: true - он заоверрайдится

2021-05-27 12:36 UTC, TFK70 requested changes

2021-05-27 12:36 UTC, TFK70 commented on practice/my-diary/ui/button/src/appearance/appearance.styles.ts
> +  boxShadow,
Это не colorStyles
Здесь настоятельно рекомендую создать отдельную функцию для конфигурации теней

2021-05-27 12:36 UTC, TFK70 commented on practice/my-diary/ui/condition/src/Condition.tsx
> +  return match ? <Box>{children}</Box> : <Box>{}</Box>
А зачем "ничего" оборачивать в Box?

2021-05-27 12:36 UTC, TFK70 commented on practice/my-diary/ui/condition/src/Condition.tsx
> +  return match ? <Box>{children}</Box> : <Box>{}</Box>
Зачем тут вообще что-то оборачивать Box?

2021-05-27 12:36 UTC, TFK70 commented on practice/my-diary/ui/drawer/src/Drawer.tsx
> +const StyledContainer = styled.div(
Префикс Styled нужен если базовый компонент уже имеет какие-то стили, его имя уже зарезервировано и т.п., короче не пустой

В твоем случае:

1. Стилизуется обычный див
2. Название Container неуместно, т.к. в этом компоненте ничего не лежит (см. [верстку ниже)](https://github.com/atls-academy/ikorol.github.io/pull/89/files#diff-6c7b6f9ca4f7b3afc68d3cbd5bd5cd2417adbff8a54a346daa2f2fb3efc462c3R60)

Дай ему более точное название, типа Blackout

2021-05-27 12:36 UTC, TFK70 commented on practice/my-diary/ui/input/src/Input.tsx
> +        <div />
Из всех возможных вариантов - этот самый неразумный
Ты могла:

а) Воспользоваться Condition тк он у тебя уже есть
б) Использовать && (если `true && значение` - возвращается значение, если `false && значение` - возвращается) - так можно избежать и тернарных операторов, и возвращений пустых дивов (это плохо тк создается лишняя пустая DOM нода)

2021-05-27 12:36 UTC, TFK70 commented on practice/my-diary/ui/input/src/appearance/appearance.styles.ts
> +  ...createColorStyles(fontColor, backgroundColor, borderColor)(),
А где здесь createPlaceholderStyles?

2021-05-27 12:36 UTC, TFK70 commented on practice/my-diary/ui/input/src/shape/shape.styles.ts
> +  '&:placeholder': {
Цвет для плейсхолдера не имеет отношения к shape (форме инпута)
Это appearance, туда color: 'gray' как дефолтное значение пихнуть и нужно

2021-05-27 16:45 UTC, TFK70 requested changes

2021-05-27 16:45 UTC, TFK70 commented on practice/my-diary/ui/button/src/appearance/appearance.styles.ts
> +export const createShadowStyles = (boxShadow): styleFn => () => ({
Для того чтобы задать boxShadow нужно неплохо так пошевелить мозгами и зайти в документацию, так что атомизируй это (чтобы бы shadowColor,shadowWeight и прочее)

2021-05-27 16:45 UTC, TFK70 commented on practice/my-diary/ui/condition/src/Condition.tsx
> +  return match ? <Box>{children}</Box> : null
Так а зачем тут Box?

2021-05-27 16:45 UTC, TFK70 commented on practice/my-diary/ui/input/src/appearance/appearance.styles.ts
> +    color: styles,
Так а зачем styles кидать в color?
В styles находятся общие стили для placeholder, поэтому они так и называются, там лежит объект со стилями

2021-05-27 16:45 UTC, TFK70 commented on practice/my-diary/ui/input/src/appearance/appearance.styles.ts
> +  '&::placeholder': {
Почему тут '::'?

2021-05-27 17:03 UTC, ikorol3107 commented on practice/my-diary/ui/input/src/appearance/appearance.styles.ts
> +  '&::placeholder': {
@TFK70 а когда пишу '&:placeholder' , то тогда цвет плэйсхолдера не меняется

2021-05-27 17:07 UTC, TFK70 commented on practice/my-diary/ui/input/src/appearance/appearance.styles.ts
> +  '&::placeholder': {
@ikorol3107 да, тут все верно

2021-05-28 08:05 UTC, ikorol3107 commented on practice/my-diary/ui/button/src/appearance/appearance.styles.ts
> +export const createShadowStyles = (boxShadow): styleFn => () => ({
@TFK70 а почему мой вариант не подходит? Хочу понимать, зачем здесь именно shadowColor, shadowWeight и прочее. Логику короче.

2021-05-28 08:24 UTC, TFK70 commented on practice/my-diary/ui/button/src/appearance/appearance.styles.ts
> +export const createShadowStyles = (boxShadow): styleFn => () => ({
@ikorol3107 твой вариант не "не подходит", он просто не совсем удобный

Смотри как выглядит boxShadow:

```javascript
box-shadow: 12px 12px 2px 1px rgba(0, 0, 255, .2);
```
Я вот никогда не мог запомнить что тут за что отвечает, без документации тень для своего компонента ты нормально не сделаешь

А теперь смотри как у тебя будет работать createShadowStyles (через createAppearanceStyles, как положено):

```javascript
createAppearanceStyles({
   shadowOffsetX: 12,
   shadowOffsetY: 12,
   shadowBlur: 2,
   shadowSize: 1,
   shadowColor: 'purple' // условный цвет из темы
})
```

Разумеется бОльшая часть этих пропов должна быть опциональной со значением по умолчанию, чтобы каждый раз это полотно не выписывать

2021-05-28 09:22 UTC, ikorol3107 commented on practice/my-diary/ui/button/src/appearance/appearance.styles.ts
> +export const createShadowStyles = (boxShadow): styleFn => () => ({
@TFK70 поняла, спасиб! Получается я не буду использовать shadows которые у меня сейчас есть в theme , потому-что они там именно так и заданы:
```javascript
export const shadows = {
  gray: '0 0 10px rgba(0,0,0,0.5)',
  darkGray: '2px 0 5px rgba(0,0,0,0.2)',
  violet: '0 0 10px rgba(176, 127, 236, 1)',
}
```

2021-05-28 09:23 UTC, TFK70 commented on practice/my-diary/ui/button/src/appearance/appearance.styles.ts
> +export const createShadowStyles = (boxShadow): styleFn => () => ({
@ikorol3107 да, просто тот же результат будет добиваться через switchProp

2021-05-28 15:19 UTC, TFK70 requested changes

2021-05-28 15:19 UTC, TFK70 commented on practice/my-diary/ui/theme/src/theme/colors.ts
> +  deepPurple: 'rgba(176, 127, 236, 1)',
цвета описывай в одном стиле
если у тебя везде hex - то и придерживайся  hex

2021-05-28 15:19 UTC, TFK70 commented on practice/my-diary/fragments/form-add-post/src/FormAddPost.tsx
> +          borderRadius='round'
Ни малейшего понятия о степени закругления. Если я задаю borderRadius - я уже понимаю что бордер будет с закруглением, вопрос - насколько сильным

2021-05-28 15:19 UTC, TFK70 commented on practice/my-diary/ui/background/src/Background.tsx
> +    height: '100vh',
@ikorol3107 [?](https://github.com/atls-academy/ikorol.github.io/pull/89/files#r637390227)

2021-05-28 15:19 UTC, TFK70 commented on practice/my-diary/ui/button/src/Button.styles.ts
> +  border: '1px solid',
Для бордера должна быть своя функция

Я бы удивился если бы я хотел уменьшить размер кнопки до 40px и у меня бы появился бордер

2021-05-28 15:19 UTC, TFK70 commented on practice/my-diary/ui/button/src/shape/shape.styles.ts
> +  width,
Нельзся
 width всегда 100%, иначе вся флексовость теряет смысл

2021-05-28 15:19 UTC, TFK70 commented on practice/my-diary/ui/condition/src/Condition.tsx
> +  return match ? children : null
Лучше возвращать {}
Про null я вроде уже рассказывал, его в случае чего очень трудно дебажить тк его тип не определен, так что лучше по-максимуму избегать его использования

2021-05-28 15:19 UTC, TFK70 commented on practice/my-diary/ui/input/src/parts/StyledInput.styles.ts
> +export const appearanceStyles = switchProp(prop('color', 'normal'), () => ({
normal color? 
это какой?

2021-05-28 15:19 UTC, TFK70 commented on practice/my-diary/ui/list/src/Item.tsx
> +    width: '470px',
Все правильно тут было, оставь width 100%
Как я уже упоминал, иначе весь прикол флексов исчезает. Смотри на родительский блок, он должен регулировать ширину

2021-05-28 15:19 UTC, TFK70 commented on practice/my-diary/ui/list/src/Item.tsx
> +          <Box position='relative' left='11px' border='none'>
relative и left?

2021-05-28 15:38 UTC, ikorol3107 commented on practice/my-diary/ui/background/src/Background.tsx
> +    height: '100vh',
@TFK70 с cover остается белой часть экрана снизу.

2021-05-28 15:39 UTC, TorinAsakura commented on practice/my-diary/ui/background/src/Background.tsx
> +    height: '100vh',
скрин прикладывай на будущее, чтобы нам не пришлось включать телеметрию

2021-05-28 15:50 UTC, TFK70 commented on practice/my-diary/ui/background/src/Background.tsx
> +    height: '100vh',
@ikorol3107 все правильно, у тебя Background работает как надо
Он полностью покрывает бекграунд блока в котором используется, но тебе же нужно задать бекграунд в целом для всего приложения

В таком случае задавай 100vh снаружи
И justifyContent из бекграунда убери

2021-05-31 06:55 UTC, ikorol3107 commented on practice/my-diary/ui/list/src/Item.tsx
> +          <Box position='relative' left='11px' border='none'>
@TFK70 да, у relative есть свойства left, top,...итд

2021-05-31 07:01 UTC, TFK70 commented on practice/my-diary/ui/list/src/Item.tsx
> +          <Box position='relative' left='11px' border='none'>
@ikorol3107 я не могу понять чем это оправдано, ты же снова таким образом отказываешься от флексов (это равносильно marginLeft на самом деле)

2021-05-31 07:08 UTC, ikorol3107 commented on practice/my-diary/ui/list/src/Item.tsx
> +          <Box position='relative' left='11px' border='none'>
@TFK70 у меня две иконки одна на одной должна быть , а не рядом. Поэтому надо позиционировать.

2021-05-31 07:10 UTC, TFK70 commented on practice/my-diary/ui/list/src/Item.tsx
> +          <Box position='relative' left='11px' border='none'>
@ikorol3107 хотя стой, я понял в чем тут дело
Я бы на твоем месте не стал использовать здесь свг, в них вообще никакого смысла нет. Попробуй сделать контейнер с максимальным бордер радиусом и бордером с нужной шириной и цветом, а внутри этот контейнера либо с помощью Condition показывай фиолетовый блок который будет заполнять твой контейнер, либо сделай условие для backgroundColor (если активо то backgroundColor фиолетовый), последнее наиболее предпочтительно тк не создается доп. DOM нода и стили будут более отказоустойчивыми, фиолетовый круг будет гарантировано внутри кольца

2021-05-31 09:33 UTC, TFK70 requested changes

2021-05-31 09:33 UTC, TFK70 commented on practice/my-diary/fragments/diary/src/Diary.tsx
> +      <Column width='600px'>
Ну опять пиксели?
Попробуй сверстать все чисто на пикселях и поиграть с размерами окна
В определенных местах результат тебе не понравится, поэтому вместо пикселей нужно использовать % или что-то из флексовой оперы (относительные величины, в общем)

2021-05-31 09:33 UTC, TFK70 commented on practice/my-diary/fragments/diary/src/Diary.tsx
> +      <Column width='600px'>
Например попробуй width у этой колонки сделать 1000-1500 пикселей и уменьшай ширину экрана, запомни как все примерно происходило, поменяй ширину колонки с пикселей на 80% и сделай то же самое
Результат на лицо

2021-05-31 09:33 UTC, TFK70 commented on practice/my-diary/fragments/form-add-post/src/FormAddPost.tsx
> +      <Box justifyContent='center' width='270px'>
То же самое

2021-05-31 09:33 UTC, TFK70 commented on practice/my-diary/fragments/form-add-post/src/FormAddPost.tsx
>        <Row justifyContent='center' backgroundColor='white' height='90px'>
Тоже пксели

2021-05-31 09:33 UTC, TFK70 commented on practice/my-diary/ui/filter/src/Filter.tsx
> +        <Box key={option} width='100px'>
Тооже пиксели

2021-05-31 09:33 UTC, TFK70 commented on practice/my-diary/ui/input/src/addons/ClearButton.tsx
> +  <Box width='100px'>
Пиксели Пиксели Пиксели

2021-05-31 09:33 UTC, TFK70 commented on practice/my-diary/ui/list/src/Item.tsx
> +          width='16px'
Пиксели позволительны разве что здесь
Тебе ни к чему четко пропорциональные уменьшения размеров твоей точки, так что здесь пиксели - ок
Аналогично с размерами инпутов или кнопок, например. Их высоту тоже лучше задавать в пикселях, потому что иначе при ее сильном уменьшении кнопка начинает слабо походить на кнопку (а нам это не надо), а вот ширина у них должна быть просентная

2021-05-31 19:00 UTC, TFK70 requested changes

2021-05-31 19:00 UTC, TFK70 commented on practice/my-diary/ui/background/src/Background.tsx
> +    height: 'cover',
Что делает `height:'cover'`?

2021-05-31 19:00 UTC, TFK70 commented on practice/my-diary/ui/input/src/appearance/appearance.styles.ts
> +  ...createColorStyles(fontColor, backgroundColor, borderColor)(),
[?](https://github.com/atls-academy/ikorol.github.io/pull/89/files#r640578304)

2021-05-31 19:00 UTC, TFK70 commented on practice/my-diary/ui/list/src/List.tsx
> +    <Column backgroundColor='white' minHeight='250px'>
У Column height всегда 100%
Если это необходимо для поддержки размеров основного белого блока - это надо указать в параметрах основного белого блока, здесь для подобного не место

2021-06-01 08:51 UTC, ikorol3107 commented on practice/my-diary/ui/input/src/appearance/appearance.styles.ts
> +  ...createColorStyles(fontColor, backgroundColor, borderColor)(),
@TFK70 не могу понять, как передать стили псевдоэлемента здесь `...createPlaceholderStyles(?)()`
?

2021-06-01 08:55 UTC, TFK70 commented on practice/my-diary/ui/input/src/appearance/appearance.styles.ts
> +  ...createColorStyles(fontColor, backgroundColor, borderColor)(),
@ikorol3107 туда пойдет объект placeholderStyles
Пример использования:

```javascript
createAppearanceStyles({
   placeholderStyles: {
      color: 'purple',
      fontSize: '12px'
   }
})

```

2021-06-01 14:39 UTC, ikorol3107 commented on practice/my-diary/ui/input/src/appearance/appearance.styles.ts
> +  ...createColorStyles(fontColor, backgroundColor, borderColor)(),
@TFK70 не получается(    Мой код:
```javascript
export const createAppearanceStyles = ({
  fontColor,
  backgroundColor,
  borderColor,
  placeholderStyles = {
    '&::placeholder': {
      color: 'silver',
    },
  },
}: InputAppearanceStyles): styleFn => () => ({
  ...createColorStyles(fontColor, backgroundColor, borderColor)(),
  ...createPlaceholderStyles(placeholderStyles)(),
})
```

2021-06-01 14:42 UTC, TFK70 commented on practice/my-diary/ui/input/src/appearance/appearance.styles.ts
> +  ...createColorStyles(fontColor, backgroundColor, borderColor)(),
@ikorol3107 ну так:

```javascript
'&::placeholder': {
   '&::placeholder': {
         color: 'silver'
       }
   }
```

так и не должно работать

2021-06-01 14:59 UTC, ikorol3107 commented on practice/my-diary/ui/input/src/appearance/appearance.styles.ts
> +  ...createColorStyles(fontColor, backgroundColor, borderColor)(),
@TFK70 шайзе, я поняла, почему я так тупила - забыла второе двоеточие поставить и  начала придумывать идиотские варианты, т.к. не работал код без него. %-/

2021-06-01 15:14 UTC, TFK70 requested changes

2021-06-01 15:14 UTC, TFK70 commented on practice/my-diary/fragments/main-page-header/src/MainPageHeader.tsx
> +        <Text fontSize='large' fontWeight='bold' color='white' textAlign='center'>
Зачем тут textAlign?

2021-06-01 15:14 UTC, TFK70 commented on practice/my-diary/ui/background/src/Background.tsx
> -    height: 'cover',
Ну тогда у тебя Background будет отрабатывать не как надо
Он должен по умолчанию полностью занимать блок в котором он находится, иначе это не бекграунд

2021-06-01 16:55 UTC, ikorol3107 commented on practice/my-diary/fragments/main-page-header/src/MainPageHeader.tsx
> +        <Text fontSize='large' fontWeight='bold' color='white' textAlign='center'>
@TFK70 а без textAlign при изменении размеров окна текст начинает жаться к левому краю.

2021-06-01 17:05 UTC, ikorol3107 commented on practice/my-diary/ui/background/src/Background.tsx
> -    height: 'cover',
@TFK70  `height: '100%'` ?

2021-06-01 17:18 UTC, TFK70 commented on practice/my-diary/ui/background/src/Background.tsx
> -    height: 'cover',
@ikorol3107 еще варианты?

2021-06-01 17:30 UTC, ikorol3107 commented on practice/my-diary/ui/background/src/Background.tsx
> -    height: 'cover',
@TFK70 100vh

2021-06-01 17:30 UTC, TFK70 commented on practice/my-diary/ui/background/src/Background.tsx
> -    height: 'cover',
@ikorol3107 и в чем между ними будет разница?

2021-06-01 17:57 UTC, ikorol3107 commented on practice/my-diary/ui/background/src/Background.tsx
> -    height: 'cover',
@TFK70  Проценты измеряются относительно родителя, а vh относительно высоты окна.

2021-06-01 17:57 UTC, TFK70 commented on practice/my-diary/ui/background/src/Background.tsx
> -    height: 'cover',
@ikorol3107 угу
что нам больше тут подходит?

2021-06-01 18:02 UTC, ikorol3107 commented on practice/my-diary/ui/background/src/Background.tsx
> -    height: 'cover',
@TFK70 100vh

2021-06-01 18:06 UTC, TFK70 commented on practice/my-diary/ui/background/src/Background.tsx
> -    height: 'cover',
@ikorol3107 но представь что у тебя есть компонент 40% на 40% по середине экрана, ему тебе нужно задать картинку на задний фон, делать это по логике вещей нужно с помощью компонента Background, но возможно ли это будет если поставить ему 100vh?

2021-06-02 11:55 UTC, TFK70 approved these changes

2021-06-03 15:28 UTC, TorinAsakura approved these changes

2021-06-03 15:28 UTC, merged