feat(my-diary): add mobile view using breakpoints
Atlantis-Academy/frontend-study-ikorol pull request #92
Opened 2021-06-04 16:42 UTC by ikorol3107

affects: @fragments/diary, @fragments/form-add-post, @fragments/post-list, @practice/my-diary,
@ui/drawer

ISSUES CLOSED: #78

2021-06-05 15:15 UTC, TFK70 commented
@ikorol3107 https://developer.mozilla.org/ru/docs/Glossary/Viewport

2021-06-05 16:05 UTC, ikorol3107 commented
> @ikorol3107 https://developer.mozilla.org/ru/docs/Glossary/Viewport

@TFK70 вношу изменения в хедер, пересобираю приложение и внесенные строчки пропадают, возвращаясь к первоначальному виду. Это ретроградный меркурий или я что-то не учитываю?

2021-06-05 16:06 UTC, TFK70 commented
@ikorol3107 как именно изменения вносишь?

2021-06-05 16:09 UTC, ikorol3107 commented
> @ikorol3107 как именно изменения вносишь
папка dist - файл index.html 
вствляю в хэдере `<meta name='viewport' content='width=device-width,initial-scale=1.0'/>`

2021-06-05 16:11 UTC, TFK70 commented
@ikorol3107 а зачем дист?
у нас html генерится через плагин для вебпака, зайди в его доку, там в секцию конфигурации, там и нужно указать все доп надстройки для темплейта

2021-06-06 06:15 UTC, TFK70 commented
@ikorol3107 контент в drawer'е слегка поехал

https://user-images.githubusercontent.com/62806448/120914497-02e86980-c6b8-11eb-9cf8-e8eaeebb3299.MP4

Чтобы протестить на реальной мобилке используй [localtunnel](https://github.com/localtunnel/localtunnel):

1. `yarn global add localtunnel`
2. Запусти приложение
3. `lt --port *порт приложения* --local-host localhost`

2021-06-07 12:03 UTC, TFK70 approved these changes

2021-06-08 16:57 UTC, TorinAsakura requested changes
Проще пользоваться точными величинами всегда. Ведь все прототипы которые мы делаем в Figma - в пикселях

2021-06-08 16:57 UTC, TorinAsakura commented on practice/my-diary/fragments/post-list/src/PostList.tsx
> +      minHeight={['60%', '60%', '30%']}
для чего тут задаётся минимальный порог высоты? и почему снова в %?

2021-06-08 16:57 UTC, TorinAsakura commented on practice/my-diary/fragments/form-add-post/src/FormAddPost.tsx
> +        <Column alignItems='center' width='70%'>
никаких % только {[…,…,…]}

2021-06-08 16:57 UTC, TorinAsakura commented on practice/my-diary/ui/drawer/src/Drawer.tsx
> +      <StyledDrawer visible={isVisible} boxShadow='darkGray' width={['70%', '50%', '40%']}>
снова %

2021-06-11 10:45 UTC, TFK70 requested changes

2021-06-11 10:45 UTC, TFK70 commented on practice/my-diary/webpack.config.ts
> +    meta: [
Обрати внимание на поле mobile в [доке](https://github.com/jaketrent/html-webpack-template) темплейта

2021-06-15 14:08 UTC, TFK70 requested changes
И тем временем на десктопе что-то пошло не так:

![image](https://user-images.githubusercontent.com/62806448/122067520-152b7b80-ce0d-11eb-957c-e119c5dbcc13.png)

2021-06-15 14:08 UTC, TFK70 commented on practice/my-diary/webpack.config.ts
> +    mobile: true,
Да, но мета-теги тогда зачем?

2021-06-17 08:25 UTC, TFK70 requested changes

2021-06-17 08:25 UTC, TFK70 commented on practice/my-diary/ui/filter/src/Filter.tsx
> +        <Box key={option} width='100px'>
Ситуация явно ухудшилась:

![image](https://user-images.githubusercontent.com/62806448/122359740-3d32f000-cf6f-11eb-82da-1fc59c9640de.png)

2021-06-17 08:25 UTC, TFK70 commented on practice/my-diary/ui/filter/src/Filter.tsx
> +        <Box key={option} width='100px'>
Но в мобилке все ок

2021-06-17 09:36 UTC, ikorol3107 commented on practice/my-diary/ui/filter/src/Filter.tsx
> +        <Box key={option} width='100px'>
@TFK70 странно, у меня все норм отражается. Ок сейчас попробую размер шрифта поменять

2021-06-17 09:41 UTC, TFK70 commented on practice/my-diary/ui/filter/src/Filter.tsx
> +        <Box key={option} width='100px'>
@ikorol3107 разница в разрешении экранов, ничего странного
Можешь попробовать textOverflow, но лучше конечно чтобы все слово в кнопку умещалось

2021-06-17 09:47 UTC, TFK70 requested changes

2021-06-17 09:47 UTC, TFK70 commented on practice/my-diary/fragments/diary/src/Diary.tsx
> +      height='100vh'
На самом деле так быть не должно
У бекграунда в дефолт пропсах должны быть width и height по 100%
Чтобы он не обрезался нужно задать body и рутовому блоку height 100% в глобалсах

2021-06-17 09:47 UTC, TFK70 commented on practice/my-diary/fragments/diary/src/Diary.tsx
> +      justifyContent='center'
И так тоже лучше не делать, чтобы отпозиционировать все по центру воспользуйся дополнительным Row, бекграунд должен отвечать только за задний фон

2021-06-17 11:35 UTC, ikorol3107 commented on practice/my-diary/fragments/diary/src/Diary.tsx
> +      height='100vh'
@TFK70  тоесть я в вёбпак конфиге должна как-то эти height 100% задать?

2021-06-17 11:36 UTC, TFK70 commented on practice/my-diary/fragments/diary/src/Diary.tsx
> +      height='100vh'
@ikorol3107 а зачем в вебпак конфиге? У тебя же для глобальных стилей отдельное место есть

2021-06-17 11:56 UTC, ikorol3107 commented on practice/my-diary/fragments/diary/src/Diary.tsx
> +      height='100vh'
@TFK70 блок body формируется в html файле при помощи вебпак конфига, поэтому я так подумала. Какое отдельное место для глобальных стилей ты имеешь в виду? я не могу сообразить.

2021-06-17 11:57 UTC, TFK70 commented on practice/my-diary/fragments/diary/src/Diary.tsx
> +      height='100vh'
@ikorol3107 globals в theme
Просто заинжектить css стили на body и рутовый блок

2021-06-17 12:16 UTC, TFK70 requested changes

2021-06-17 12:16 UTC, TFK70 commented on practice/my-diary/ui/theme/src/globals.ts
> +    'html, body, root': {
1. В доме нет элемента `<root></root>`
2. Руту паддинги не нужны

2021-06-17 12:35 UTC, TFK70 submitted a review, later dismissed

2021-06-17 15:50 UTC, TorinAsakura submitted a review, later dismissed

2021-06-17 15:51 UTC, TorinAsakura commented
@ikorol3107 коммиты не подписаны, не пройдёт

2021-06-17 16:33 UTC, ikorol3107 commented
> @ikorol3107 коммиты не подписаны, не пройдёт

@TorinAsakura имеешь ввиду краткое описание к коммиту? вроде я везде их писала.

2021-06-17 16:34 UTC, TFK70 commented
> > @ikorol3107 коммиты не подписаны, не пройдёт
> 
> @TorinAsakura имеешь ввиду краткое описание к коммиту? вроде я везде их писала.

gpg  подпись

2021-06-17 16:39 UTC, TFK70 commented
@ikorol3107 проверь через `git config --list` поля `user.signingkey` (там должен быть ключ) и `commit.gpgsign` который должен быть в true

2021-06-18 07:24 UTC, ikorol3107 commented
> @ikorol3107 проверь через `git config --list` поля `user.signingkey` (там должен быть ключ) и `commit.gpgsign` который должен быть в true

@TFK70 а нет у меня ничего там кроме email и имени . Делала еще в мае на этом ноуте пару ключей ssh и gpg ключей, куда они делись вобще не понимаю. сейчас слеоаю новые...

2021-06-18 07:28 UTC, TFK70 commented
@ikorol3107 после настройки сделай ребейз в интерактивном режиме
Нужно пофиксить коммиты с 4a2f506 по 98c265e

2021-06-18 08:49 UTC, TFK70 approved these changes

2021-06-22 18:16 UTC, TorinAsakura approved these changes

2021-06-22 18:16 UTC, merged