Feat/create public package
Atlantis-Academy/frontend-study-ikorol pull request #93
Opened 2021-06-24 12:52 UTC by ikorol3107

2021-06-24 13:39 UTC, TFK70 requested changes

2021-06-24 13:39 UTC, TFK70 commented on packages/todoList/layout/Layout.tsx
> +import styled                                              from '@emotion/styled'
А почему это не в src?

2021-06-24 13:39 UTC, TFK70 commented on packages/todoList/theme/globals.ts
> +export const injectGlobalStyles = () => {
Зачем инжектить глобальные стили в пакете который рендерит лист?

2021-06-24 13:39 UTC, TFK70 commented on packages/todoList/theme/theme/colors.ts
> +  silver: '#c0c0c0',
Я вообще сомневаюсь что этому пакету нужна тема, если честно
Попробуй сделать цвета конфигурируемыми, можешь попробовать разделить цвета на `primary`, `secondary` и тд, тем самым задавая цветовую палитру вместо того чтобы каждому элементу давать конкретный цвет

2021-06-24 13:39 UTC, TFK70 commented on packages/todoList/theme/theme/colors.ts
> +  silver: '#c0c0c0',
Ну это было к тому что как минимум 80% цветов описанных здесь не используются

2021-06-24 13:39 UTC, TFK70 commented on packages/todoList/theme/theme/fontSizes.ts
> +  giant: '1.5vw',
1. Сохраняй единый стиль, если у тебя везде размер в пикселях (но описываешь его как number) - то и пиши во всех остальных местах так же
2. См. коммент выше

2021-06-24 13:39 UTC, TFK70 commented on packages/todoList/theme/index.ts
> +export * from './ThemeProvider'
А он тут что забыл?

2021-06-24 13:39 UTC, TFK70 commented on practice/my-diary/ui/input/src/parts/StyledInput.styles.ts
> +export const largeFontSizeStyles = ({ theme }) =>
В этом пакете где-то инпут используется?

2021-06-25 12:30 UTC, ikorol3107 commented on packages/todoList/layout/Layout.tsx
> +import styled                                              from '@emotion/styled'
@TFK70 имеешь ввиду, что layout должен в src быть?

2021-06-25 12:31 UTC, TFK70 commented on packages/todoList/layout/Layout.tsx
> +import styled                                              from '@emotion/styled'
ну так у тебя структура пакета не соблюдена, исходники находятся вне src

2021-06-29 13:53 UTC, TFK70 requested changes

2021-06-29 13:53 UTC, TFK70 commented on practice/my-diary/fragments/post-list/src/PostList.tsx
> +import { TodoList }                              from '../../../../../packages/todoList'
Так а задача какая была?

2021-06-29 13:53 UTC, TFK70 commented on practice/my-diary/fragments/post-list/src/PostList.tsx
> +import { TodoList }                              from '../../../../../packages/todoList'
И у тебя конфликты

2021-06-30 05:18 UTC, ikorol3107 commented on practice/my-diary/fragments/post-list/src/PostList.tsx
> +import { TodoList }                              from '../../../../../packages/todoList'
@TFK70 чтоб создать публичный пакет с именем @academy/ikorol , на npmjs.com должен быть  нэймспэйс @academy для нас с Сашей обоих, чтоб уже там мы каждый свой скоуп сделали. Или я не правильно понимаю? Сейчас такого нет.

2021-06-30 08:46 UTC, TFK70 commented on practice/my-diary/fragments/post-list/src/PostList.tsx
> +import { TodoList }                              from '../../../../../packages/todoList'
Да, но у тебя пакет корректно отрабатывает если запаблить его под твоим намспейсом?

2021-06-30 12:26 UTC, ikorol3107 commented on practice/my-diary/fragments/post-list/src/PostList.tsx
> +import { TodoList }                              from '../../../../../packages/todoList'
@TFK70 запаблила под своим нэймспейсом, две ошибки выдал - обе о том что не хватает соответствующих загрузчиков:
```javascript
ERROR in ../../node_modules/@ikorol/todolist/src/TodoList.tsx 6:21
Module parse failed: Unexpected token (6:21)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| import { Item }           from './Item'
| 
> export const TodoList: any = ({ notes, setNotes, visibleNotes, deleteItem, toggleStatus }) => {
|   return (
|     <Column backgroundColor='white'>
 @ ../../node_modules/@ikorol/todolist/src/index.ts 1:0-26 1:0-26
```

и вторая:
```javascript
ERROR in ../../node_modules/@ikorol/todolist/src/Item.tsx 39:4
Module parse failed: Unexpected token (39:4)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|   }
|   return (
>     <>
|       <Row
|         alignItems='center'
 @ ../../node_modules/@ikorol/todolist/src/index.ts 2:0-22 2:0-22
```

2021-06-30 12:47 UTC, TFK70 commented on practice/my-diary/fragments/post-list/src/PostList.tsx
> +import { TodoList }                              from '../../../../../packages/todoList'
@ikorol3107 зачем тебе делать тайпчеки в нод модулях?

2021-07-01 05:22 UTC, ikorol3107 commented on practice/my-diary/fragments/post-list/src/PostList.tsx
> +import { TodoList }                              from '../../../../../packages/todoList'
@TFK70 Не до конца понимаю что имеешь ввиду

2021-07-01 13:53 UTC, ikorol3107 commented on practice/my-diary/fragments/post-list/src/PostList.tsx
> +import { TodoList }                              from '../../../../../packages/todoList'
@TFK70 добавила tsconfig файл : 
```javascript
{
  "extends": "@atlantis-lab/tsconfig/tsconfig.base.json",
  "include": ["./src"],
  "compilerOptions": {
    "outDir": "dist"
  }
}
``` 
это package.json моего пакета:
```javascript
{
  "name": "@ikorol/todolist",
  "version": "0.0.4",
  "license": "MIT",
  "main": "src/index.ts",
  "devDependencies": {
    "@types/styled-system": "^5.1.10"
  },
  "dependencies": {
    "@emotion/css": "^11.1.3",
    "@emotion/react": "^11.1.5",
    "@emotion/styled": "^11.1.5",
    "react": "^17.0.1",
    "styled-system": "^5.1.0"
  },
  "files": [
    "dist"
  ],
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "build": "tsc"
  },
  "keywords": [
    "todoList"
  ],
  "author": "ikorol3107@gmail.com",
  "description": "todoList"
}
```
При этом в нод модулях не dist компилируется, а папка src с одним единственным файлом в ней - index.ts
Что я делаю не так?

2021-07-01 13:59 UTC, TFK70 commented on practice/my-diary/fragments/post-list/src/PostList.tsx
> +import { TodoList }                              from '../../../../../packages/todoList'
1. Локальные компоненты находятся в src?
2. Зачем тебе этот скрипт `"test": "echo \"Error: no test specified\" && exit 1"`?
3. Пробовала просто запускать скрипт build?  В дисте находятся все js файлы?
4. Не вижу в зависимостях @atlantis-lab/actl или @atlantis-lab/config, откуда у тебя тогда твой тсконфиг наследуется?

2021-07-03 11:29 UTC, TFK70 requested changes

2021-07-03 11:29 UTC, TFK70 commented on packages/todoList/package.json
> +    "@atlantis-lab/tsconfig": "^0.1.12",
Конфиг идет вместе с actl

2021-07-03 11:29 UTC, TFK70 commented on packages/todoList/src/TodoList.tsx
> +export const TodoList: any = ({ notes, setNotes, visibleNotes, deleteItem, toggleStatus }) => {
Осталось только типизировать

Создай `todolist.interface.ts` с интерфейсом для твоего компонента, все текущие файлы с компонентами переименуй в `text.component.tsx`, `todolist.component.tsx` и тд по аналогии

2021-07-03 11:29 UTC, TFK70 commented on packages/todoList/src/icons/HeartIcon.tsx
> +const StyledHeartIcon = styled.i`
Мы же так не делаем, опиши js объектом

2021-07-03 11:29 UTC, TFK70 commented on tsconfig.json
> +  "include": ["lessons/**/**/*", "practice/**/**/*", "packages/**/*"]
Твоего пакета не должно быть в ворксейсах

2021-07-05 11:01 UTC, ikorol3107 commented on packages/todoList/src/TodoList.tsx
> +export const TodoList: any = ({ notes, setNotes, visibleNotes, deleteItem, toggleStatus }) => {
@TFK70 переделала, но теперь приложение не отрисовывается. Консоль:
_Uncaught Error: Invalid hook call. Hooks can only be called inside of the body of a function component_. 

Мой todoList.component.tsx:
```javascript
import React              from 'react'
import { FC }             from 'react'

import { Item }           from './item.component'
import { Column, Layout } from './layout'
import { TodoListProps }  from './todoList.interface'

export const TodoList: FC<TodoListProps> = ({
  notes,
  setNotes,
  visibleNotes,
  deleteItem,
  toggleStatus,
}) => {
  return (
    <Column backgroundColor='white'>
      <Layout flexBasis={50} />
      {visibleNotes.map(item => (
        <Item
          notes={notes}
          setNotes={setNotes}
          note={item}
          key={item.id}
          deleteItem={deleteItem}
          toggleStatus={toggleStatus}
        />
      ))}
    </Column>
  )
}
```
Мой todoList.interface.ts:
```javascript
export interface NotesObject {
  note?: string | number
  important?: boolean
  liked?: boolean
  id: number
}

export type Callback = (id: number, note?: NotesObject, value?: string) => NotesObject[]

export interface TodoListProps {
  notes: string[]
  setNotes: () => string[]
  visibleNotes: NotesObject[]
  deleteItem: Callback
  toggleStatus: Callback
}
```

2021-07-05 11:06 UTC, TFK70 commented on packages/todoList/src/TodoList.tsx
> +export const TodoList: any = ({ notes, setNotes, visibleNotes, deleteItem, toggleStatus }) => {
@ikorol3107 дело-то тут очевидно не в названиях файлов. Ты же помнишь что провоцирует эту ошибку?
Ищи все места где у тебя используются хуки и удостоверься что они вызываются внутри компонента

> import { TodoListProps }  from './todoList.interface'

И лучше поменяй на `todo-list.interface.ts`, камелкейс здесь как-то странно смотрится

2021-07-05 12:28 UTC, ikorol3107 commented on packages/todoList/src/TodoList.tsx
> +export const TodoList: any = ({ notes, setNotes, visibleNotes, deleteItem, toggleStatus }) => {
@TFK70 да уже три раза проверила , все хуки на своих местах.

- _И лучше поменяй на todo-list.interface.ts, камелкейс здесь как-то странно смотрится_ - ок, поменяла.

2021-07-05 15:18 UTC, TFK70 requested changes

2021-07-05 15:18 UTC, TFK70 commented on packages/todoList/package.json
> +    "@atlantis-lab/tsconfig": "^0.1.12",
Ну вообще скорее надо было убрать  `@atlsntis-lab/tsconfig` и оставить actl, но раз уж на то пошло то просто `@atlantis-lab/config`

2021-07-05 15:18 UTC, TFK70 commented on practice/my-diary/fragments/post-list/package.json
> +    "@ui/theme": "0.0.0",
А зачем здесь тема?

2021-07-05 15:32 UTC, ikorol3107 commented on practice/my-diary/fragments/post-list/package.json
> +    "@ui/theme": "0.0.0",
ок, хорошо. @TFK70 у меня после обновления зависимостей все заработало, но в eslint не прошел проверку коммит - каждый компонент пакета получил ошибку:
 _Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
The file does not match your project config: packages/todoList/src/text/text.component.tsx.
The file must be included in at least one of the projects provided_ 

это решается установкой @typescript-eslint/parser или по-другому?

2021-07-05 16:02 UTC, TFK70 commented on practice/my-diary/fragments/post-list/package.json
> +    "@ui/theme": "0.0.0",
@ikorol3107 такой ошибки вообще быть не должно по идее
Сделай коммит, посмотрю

2021-07-06 08:40 UTC, TFK70 commented on practice/my-diary/fragments/post-list/package.json
> +    "@ui/theme": "0.0.0",
@ikorol3107 добавь директорию с пакетом в корневой tsconfig в includes (или вообще убери это поле)

2021-07-06 08:42 UTC, TFK70 commented on practice/my-diary/fragments/post-list/package.json
> +    "@ui/theme": "0.0.0",
@ikorol3107 https://www.typescriptlang.org/tsconfig#include
Там есть дефолтное значение этого поля

2021-07-06 11:05 UTC, TFK70 requested changes

2021-07-06 11:05 UTC, TFK70 commented on packages/todoList/src/index.ts
> +export * from './todoList.component'
Так камелкейс везде нужно бы убрать

![image](https://user-images.githubusercontent.com/62806448/124579150-4cb7a180-de68-11eb-8b73-779e1198d5c6.png)

2021-07-06 11:05 UTC, TFK70 commented on packages/todoList/src/item.component.tsx
> +  const colors = {
Я бы на твоем месте для них отдельный файл завел (ну или в theme так же вынес)

2021-07-06 11:05 UTC, TFK70 commented on practice/my-diary/package.json
> +    "@typescript-eslint/parser": "^4.28.1",
Он тут не нужен

2021-07-06 15:22 UTC, TFK70 requested changes

2021-07-06 15:22 UTC, TFK70 commented on packages/todoList/src/theme/index.ts
> +export * from './theme.component'
почему component?

2021-07-06 15:22 UTC, TFK70 commented on packages/todoList/src/theme/theme.component.tsx
> +}
У файла расширение .tsx, но никакого jsx тут вроде бы нет

2021-07-06 15:22 UTC, TFK70 commented on packages/todoList/src/todo-list.interface.ts
> +  setNotes: () => string[]
setNotes это же колбек который идет из useState?

2021-07-08 11:30 UTC, ikorol3107 commented on packages/todoList/src/todo-list.interface.ts
> +  setNotes: () => string[]
> setNotes это же колбек который идет из useState?

@TFK70 да

2021-07-08 11:32 UTC, TFK70 commented on packages/todoList/src/todo-list.interface.ts
> +  setNotes: () => string[]
@ikorol3107 тогда его типизация явно неверная
Судя по этому типу он выглядит как:  setNotes() и при этой записи гарантированно возвращает массив строк

2021-07-08 12:14 UTC, ikorol3107 commented on packages/todoList/src/todo-list.interface.ts
> +  setNotes: () => string[]
@TFK70 значит получается так:
```javascript
export interface TodoListProps {
  notes: string[]
  setNotes: () => NotesObject[]
  visibleNotes: NotesObject[]
  deleteItem: Callback
  toggleStatus: Callback
}
```

2021-07-08 12:15 UTC, TFK70 commented on packages/todoList/src/todo-list.interface.ts
> +  setNotes: () => string[]
@ikorol3107 засунь функцию в console.log и проверь
заодно обрати внимание на то как ты ее используешь

2021-07-08 13:25 UTC, TFK70 commented on packages/todoList/src/todo-list.interface.ts
> +  setNotes: () => string[]
@ikorol3107 ты понимаешь зачем тебе это надо и как оно должно работать?

2021-07-08 15:11 UTC, ikorol3107 commented on packages/todoList/src/todo-list.interface.ts
> +  setNotes: () => string[]
@TFK70 я понимаю, что интерфейсы нужны для проверки типов свойств. Понимаю, что setNotes - это функция. Но четкого порядка в голове по этой теме нет пока.

2021-07-11 15:27 UTC, TFK70 approved these changes

2021-07-11 17:17 UTC, TorinAsakura approved these changes

2021-07-11 17:17 UTC, merged