chore(my-diary): migrate to yarn2
Atlantis-Academy/frontend-study-ikorol pull request #94
Opened 2021-08-02 12:08 UTC by ikorol3107

2021-08-02 12:29 UTC, TFK70 commented
@ikorol3107 ты проходила гайд? Все эксперименты с кастомным app, document и прочим тебе было необходимо делать на тестовом проекте который хотя бы запускается, там понять как это работает и потом внедрять к себе. 
Сейчас у тебя ни app, ни pages не оформлены как нужно, это и не должно работать в таком виде.

Если нужны примеры более приближенные к структуре твоего проекта - смотри [серенити](https://github.com/atls/serenity/tree/dev/frontend/site/app)

2021-08-03 18:37 UTC, ikorol3107 commented
@TFK70 я поменяла структуру, как я поняла принцип судя по гайду, но совершенно плыву в кастомном эпп и документс. Требуется помощь, не понимаю их глобально

2021-08-03 18:38 UTC, TorinAsakura commented
@ikorol3107 @ikorol3107 
Ну иди в дискорд

2021-08-03 18:42 UTC, ikorol3107 commented
> @ikorol3107 @ikorol3107
> Ну иди в дискорд

Можно, пожалуйста, сделать созвон завтра в первой половине дня? В любое время когда удобно

2021-08-03 18:42 UTC, TorinAsakura commented
@ikorol3107 Как угодно

2021-08-07 10:34 UTC, TFK70 requested changes

2021-08-07 10:34 UTC, TFK70 commented on practice/my-diary/app/src/index.ts
> +import { oathkeeperAuth } from '@monstrs/oathkeeper-auth'
И зачем это тут?

2021-08-07 10:34 UTC, TFK70 commented on practice/my-diary/app/src/index.ts
> +    dir: __dirname,
Вот если бы ты внимательнее смотрела комменты Саши то поняла бы что тут не так

2021-08-19 10:17 UTC, closed without merging